DROP TABLE IF EXISTS `report_reward_record`;
CREATE TABLE `report_reward_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) NOT NULL COMMENT '订单id',
  `order_items_id` bigint(20) NOT NULL COMMENT '订单详情id',
  `reward_date` datetime DEFAULT NULL COMMENT '提成日期（按天统计）',
  `category_group_UUID` varchar(255) DEFAULT NULL COMMENT '大类名称',
  `category_group_name` varchar(255) DEFAULT NULL COMMENT '大类名称',
  `buyer_manager_id` bigint(20) DEFAULT NULL COMMENT '买家交易员ID',
  `buyer_manager_name` varchar(255) DEFAULT NULL COMMENT '买家交易员姓名',
  `category_rewart_role_id` bigint(20) DEFAULT NULL COMMENT '品类提成规则id',
  `category_rewart_role` decimal(18,6) DEFAULT NULL COMMENT '品类提成规则（元/吨）',
  `buyer_rewart_role_id` bigint(20) DEFAULT NULL COMMENT '买家提成规则id',
  `seller_rewart_role_id` bigint(20) DEFAULT NULL COMMENT '卖家提成规则id',
  `status` varchar(45) DEFAULT NULL COMMENT '预留字段，是否已发放该提成  NO还未发放  YES已发放',
  `is_deleted` bit(1) DEFAULT NULL,
  `buyer_manager_org_id` bigint(20) DEFAULT NULL COMMENT '买家交易员组织ID',
  `buyer_manager_org_name` varchar(255) DEFAULT NULL COMMENT '买家交易员组织名称',
  `seller_manager_id` bigint(20) DEFAULT NULL COMMENT '卖家交易员id',
  `seller_manager_name` varchar(255) DEFAULT NULL COMMENT '卖家交易员名字',
  `seller_manager_org_id` bigint(20) DEFAULT NULL COMMENT '卖家交易员组织ID',
  `seller_manager_org_name` varchar(255) DEFAULT NULL COMMENT '卖家交易员组织名称',
  `consign_type` varchar(45) DEFAULT NULL COMMENT '卖家类型consign代运营卖家temp临采卖家',
  `weight` decimal(18,6) DEFAULT NULL COMMENT '实提重量',
  `buyer_rewart_role` decimal(18,6) DEFAULT NULL COMMENT '买家提成规则百分比',
  `seller_rewart_role` decimal(18,6) DEFAULT NULL COMMENT '卖家提成规则百分比',
  `buyer_reward_amount` decimal(18,6) DEFAULT NULL COMMENT '买家提成总金额',
  `seller_reward_amount` decimal(18,6) DEFAULT NULL COMMENT '卖家提成总金额',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(20) NOT NULL DEFAULT '0',
  `row_id` varchar(45) DEFAULT NULL,
  `parent_row_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT='提成报表';

DROP TABLE IF EXISTS `base_dict`;
CREATE TABLE `base_dict` (
  `id` int(11) NOT NULL,
  `key` varchar(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `last_updated` datetime NOT NULL DEFAULT now(),
  `last_updated_by` varchar(45) DEFAULT NULL,
  `modification_number` int(20) DEFAULT '0',
  `row_id` varchar(45) DEFAULT NULL,
  `parent_row_id` varchar(45) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`)
) COMMENT = '字典表';

DROP TABLE IF EXISTS `report_new_user_reward`;
CREATE TABLE `report_new_user_reward` (
  `id` int(11) NOT NULL,
  `add_date` datetime NOT NULL DEFAULT now() COMMENT '提成日期（按天统计）',
  `manager_id` int(11) DEFAULT NULL COMMENT '交易员ID',
  `manager_name` varchar(255) DEFAULT NULL COMMENT '交易员姓名',
  `org_id` int(11) DEFAULT NULL COMMENT '组织ID',
  `org_name` varchar(255) DEFAULT NULL COMMENT '组织名称',
  `created` datetime NOT NULL DEFAULT now(),
  `is_deleted` bit(1) DEFAULT NULL,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT now(),
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(20) NOT NULL DEFAULT '0',
  `row_id` varchar(45) DEFAULT NULL,
  `add_new_buyer` int(11) NOT NULL DEFAULT '0' COMMENT '新增买家数量',
  `add_new_seller` int(11) NOT NULL DEFAULT '0' COMMENT '新增卖家数量',
  `seller_reward_amount` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '新增卖家提成金额',
  `buyer_reward_amount` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '新增买家提成金额',
  `buyer_reward_role` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '新增买家提成规则',
  `seller_reward_role` decimal(18,6) NOT NULL DEFAULT '0.000000' COMMENT '新增卖家提成规则',
  PRIMARY KEY (`id`)
) COMMENT = '添加新客户的提成报表';

DROP TABLE IF EXISTS `report_rebate_record`;
CREATE TABLE `report_rebate_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `rebate_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '返利时间',
  `account_id` bigint(20) DEFAULT NULL COMMENT '公司ID',
  `account_name` varchar(255) DEFAULT NULL COMMENT '公司名称',
  `org_id` bigint(11) DEFAULT NULL COMMENT '组织ID',
  `org_name` varchar(255) DEFAULT NULL COMMENT '组织名称',
  `manager_id` bigint(11) DEFAULT NULL COMMENT '交易员ID',
  `manager_name` varchar(255) DEFAULT NULL COMMENT '交易员姓名',
  `contact_id` bigint(20) DEFAULT NULL COMMENT '联系人ID',
  `contact_name` varchar(255) DEFAULT NULL COMMENT '联系人姓名',
  `category_group_UUID` varchar(255) DEFAULT NULL COMMENT '大类UUID',
  `category_group_name` varchar(255) DEFAULT NULL COMMENT '大类名称',
  `weight` decimal(18,6) DEFAULT NULL COMMENT '重量',
  `amount` decimal(18,6) DEFAULT NULL COMMENT '金额',
  `rebate_amount` decimal(18,6) DEFAULT NULL COMMENT '返利总金额',
  `rebate_balance` decimal(18,6) DEFAULT NULL COMMENT '返利余额',
  `code` varchar(45) DEFAULT NULL COMMENT '单号',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` bit(1) DEFAULT NULL,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(20) NOT NULL DEFAULT '0',
  `row_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT='买家返利报表';