-- MySQL Script generated by MySQL Workbench
-- 2015年07月31日 星期五 19时42分03秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema steel_cbms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steel_cbms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `steel_cbms` ;

-- -----------------------------------------------------
-- Table `steel_cbms`.`acl_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`acl_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '角色名称',
  `code` VARCHAR(45) NOT NULL COMMENT '角色编码',
  `parent_id` BIGINT NULL DEFAULT 0 COMMENT '父角色，如业务员的父角色为总经理',
  `type` INT NOT NULL DEFAULT 0 COMMENT '查看类型，1全看/2同级+下级/3仅下级',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `status` INT NULL COMMENT '状态0锁定1正常',
  PRIMARY KEY (`id`))
  COMMENT = '角色目录';


-- -----------------------------------------------------
-- Table `steel_cbms`.`acl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`acl_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login_id` VARCHAR(45) NOT NULL COMMENT '登陆id',
  `name` VARCHAR(45) NOT NULL COMMENT '用户姓名',
  `role_id` BIGINT NOT NULL COMMENT '角色',
  `tel` VARCHAR(45) NULL COMMENT '手机号码',
  `org_id` BIGINT NOT NULL COMMENT '组织ID',
  `status` INT NOT NULL DEFAULT 1 COMMENT '状态：0锁定，1正常',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = 'CBMS登录用户 - 服务中心操作人员';


-- -----------------------------------------------------
-- Table `steel_cbms`.`acl_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`acl_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '权限名，如 查看订单',
  `code` VARCHAR(45) NOT NULL COMMENT '权限编码',
  `url` VARCHAR(200) NULL COMMENT '页面URL地址',
  `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父权限',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '权限目录';


-- -----------------------------------------------------
-- Table `steel_cbms`.`acl_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`acl_role_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT NOT NULL COMMENT '角色ID',
  `permission_id` BIGINT NOT NULL COMMENT '权限ID',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '角色权限详情';


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_organization` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL COMMENT '编码',
  `seq_code` VARCHAR(45) NOT NULL DEFAULT 'GW' COMMENT '合同前缀 如 CS-SH-000001 中的SH',
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '上级组织ID',
  `charger` BIGINT NULL COMMENT '负责人',
  `total_member` INT NOT NULL DEFAULT 0 COMMENT '人员总数',
  `status` INT NOT NULL DEFAULT 1 COMMENT '0锁定1正常',
  `credit_limit` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '可透支额度',
  `credit_limit_used` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已透支额度',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NULL,
  `modification_number` INT(20) NULL,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '业务中心组织机构';


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_province` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '省份名称',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '省份列表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_city` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '城市名称',
  `province_id` BIGINT NOT NULL COMMENT '所属省份ID',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '城市列表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_district` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '区域名称',
  `city_id` BIGINT NOT NULL COMMENT '所属城市ID',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '区县列表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL COMMENT '公司代码',
  `name` VARCHAR(45) NOT NULL COMMENT '全称',
  `addr` VARCHAR(45) NULL COMMENT '地址',
  `zip` VARCHAR(45) NULL COMMENT '邮编',
  `tel` VARCHAR(45) NULL COMMENT '公司电话',
  `balance` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '现金余额',
  `balance_freeze` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '冻结余额',
  `balance_second_settlement` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '二次结算记账余额',
  `balance_second_settlement_freeze` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '二次结算冻结余额',
  `fax` VARCHAR(45) NULL COMMENT '传真',
  `legal_person_name` VARCHAR(45) NULL COMMENT '法人姓名',
  `mobil` VARCHAR(45) NULL COMMENT '手机',
  `business` VARCHAR(100) BINARY NULL COMMENT '经营品种',
  `web_site_url` VARCHAR(45) NULL COMMENT '网址',
  `business_type` ENUM('merchant','factory','terminal','next_terminal','other') NULL COMMENT '客户类型',
  `province_id` BIGINT NULL COMMENT '省份ID',
  `city_id` BIGINT NULL COMMENT '城市ID',
  `district_id` BIGINT NULL COMMENT '区域ID',
  `proxy_factory` VARCHAR(45) NULL COMMENT '代理钢厂',
  `proxy_qty` DECIMAL(18,6) NULL DEFAULT 0 COMMENT '代理数量 eg：1111.1111吨',
  `license_code` VARCHAR(45) NULL COMMENT '营业执照注册号',
  `reg_address` VARCHAR(100) NULL COMMENT '公司注册地址',
  `org_code` VARCHAR(45) NULL COMMENT '组织机构代码',
  `bank_code` VARCHAR(45) NULL COMMENT '开户银行行号',
  `bank_name_main` VARCHAR(45) NULL COMMENT '开户银行主行 如 工商银行',
  `bank_name_branch` VARCHAR(45) NULL COMMENT '开户银行支行 如XX支行',
  `bank_provincie_id` BIGINT NULL COMMENT '银行所在省',
  `bank_city_id` BIGINT NULL COMMENT '银行所在城市',
  `account_code` VARCHAR(45) NULL COMMENT '银行账号',
  `tax_code` VARCHAR(45) NULL COMMENT '税号',
  `reg_time` DATETIME NOT NULL DEFAULT now() COMMENT '注册时间 其实就是录入时间',
  `last_bill_time` DATETIME NULL COMMENT '最后下单时间(买家)',
  `deal_total` INT NOT NULL DEFAULT 0 COMMENT '成交次数',
  `type` ENUM('buyer','seller') NOT NULL DEFAULT 'buyer' COMMENT '类型，买家还是卖家',
  `consign_type` VARCHAR(45) NULL COMMENT '代运营类型\nconsign 代运营\ntemp  临采',
  `manager_id` BIGINT NULL COMMENT '现任交易管理员',
  `status` INT NOT NULL DEFAULT 1 COMMENT '0锁定1解锁 2 买家开票资料待审核',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司列表及详情';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `url` VARCHAR(100) NOT NULL COMMENT '附件地址',
  `type` ENUM('license','org_code','tax_reg','invoice_data','legal_ID','payment_data','consign_contract','enterprise_survey','open_account_license') NOT NULL COMMENT '附件类型\npic_license(\"license\", \"营业执照\"), \n	pic_org_code(\"org_code\", \"组织机构代码证\"), \n	pic_tax_reg(\"tax_reg\", \"税务登记证\"),\n	pic_invoice_data(\"invoice_data\", \"开票资料\"), \n	pic_legal_ID(\"legal_ID\", \"法人身份证\"), \n	pic_payment_data(\"payment_data\", \"打款资料\"), \n	pic_consign_contract(\"consign_contract\", \"代运营合同\"), \n	pic_enterprise_survey(\"enterprise_survey\",\"企业调查表\"),\n	pic_open_account_license(\"open_account_license\",\"开户许可证\");',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司附件信息';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_bank` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `bank_code` VARCHAR(45) NOT NULL COMMENT '开户行编号',
  `bank_name` VARCHAR(45) NOT NULL COMMENT '开户银行主行 如 工商银行',
  `bank_name_branch` VARCHAR(45) NULL COMMENT '开户银行支行 如XX支行',
  `bank_provincie_id` BIGINT NOT NULL DEFAULT 0 COMMENT '银行所在省',
  `bank_city_id` BIGINT NOT NULL DEFAULT 0 COMMENT '银行所在城市',
  `bank_province_name` VARCHAR(45) NULL COMMENT '银行所在省',
  `bank_city_name` VARCHAR(45) NULL COMMENT '银行所在城市',
  `bank_account_code` VARCHAR(45) NOT NULL COMMENT '银行账号',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司银行账号';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_contact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `name` VARCHAR(45) NOT NULL COMMENT '姓名',
  `tel` VARCHAR(45) NOT NULL COMMENT '联系电话',
  `dept_name` VARCHAR(45) NULL COMMENT '部门',
  `qq` VARCHAR(45) NULL COMMENT 'QQ',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `is_main` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主要联系人',
  `status` INT NOT NULL DEFAULT 1 COMMENT '0锁定1正常',
  `manager` BIGINT NOT NULL COMMENT '钢为管理员ID',
  `note` VARCHAR(45) NULL,
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL COMMENT '用户身份类型，buyer seller 买家卖家',
  PRIMARY KEY (`id`))
  COMMENT = '客户公司联系人';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_contact_assign_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_contact_assign_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `reg_time` DATETIME NOT NULL COMMENT '注册时间',
  `contact_name` VARCHAR(45) NOT NULL COMMENT '客户联系人',
  `manager_ex_id` BIGINT NOT NULL COMMENT '前管理员ID',
  `manager_ex_name` VARCHAR(45) NOT NULL COMMENT '前管理员姓名',
  `manager_next_id` BIGINT NOT NULL COMMENT '现管理员ID',
  `manager_next_name` VARCHAR(45) NOT NULL COMMENT '现管理员姓名',
  `assigner_id` BIGINT NOT NULL COMMENT '分配人ID',
  `assigner_name` VARCHAR(45) NOT NULL COMMENT '分配人姓名',
  `type` ENUM('buyer','seller') NOT NULL DEFAULT 'buyer' COMMENT '分配类型 1.买家，2.卖家',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司联系人划转日志';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_contract_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_contract_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `name` VARCHAR(45) NULL COMMENT '模板名称',
  `thumbnail_url` VARCHAR(100) NULL COMMENT '缩略图地址',
  `content` TEXT NOT NULL COMMENT '合同模板',
  `type` ENUM('buyer','seller') NOT NULL COMMENT '1.采购合同 2.销售合同',
  `enabled` INT NOT NULL DEFAULT 0 COMMENT '是否启用 0未启用 1启用',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司合同模板';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_trans_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_trans_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户',
  `consign_order_code` VARCHAR(45) NULL COMMENT '代运营单号',
  `serial_number` VARCHAR(45) NULL COMMENT '相关流水号',
  `apply_type` VARCHAR(30) NULL COMMENT '申请类型:\n1 充值到资金账户\n2 支付合同货款\n3 二次结算\n4 资金账户转出\n5 抵扣二次结算账户欠款\n6 二次结算账户余额转入资金账户\n7 抵扣二次结算账户欠款\n8 合同款到账\n9 二次结算账户余额转入资金账户\n',
  `amount` DECIMAL(18,6) NOT NULL COMMENT '发生金额',
  `applyer_id` BIGINT NOT NULL COMMENT '申请人ID',
  `applyer_name` VARCHAR(45) NOT NULL COMMENT '申请人姓名',
  `serial_time` DATETIME NOT NULL COMMENT '流水时间',
  `type` ENUM('buyer','seller') NULL COMMENT '1.买家 2.卖家',
  `current_balance` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '当前余额',
  `pay_type` ENUM('balance','settlement') NULL COMMENT '支付类型\n1. 余额(balance)\n2. 结算(settlement)',
  `association_type` VARCHAR(30) NULL COMMENT '关联类型：\n１付款单号\n２代运营交易单号\n３银行流水号\n4 还款流水号',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT 0,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(45) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(45) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司账目划转详情';


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_system_opration_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_system_opration_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `operator_id` BIGINT NOT NULL COMMENT '操作者ID',
  `operator_name` VARCHAR(45) NOT NULL COMMENT '操作者姓名',
  `url` VARCHAR(100) NOT NULL COMMENT '操作的URL',
  `method` VARCHAR(45) NOT NULL COMMENT '提交的方式',
  `parameters` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '提交的参数',
  `created` DATETIME NULL DEFAULT now(),
  `created_by` VARCHAR(45) NULL,
  `last_updated` DATETIME NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NULL,
  `modification_number` INT(20) NULL,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '系统操作日志';


-- -----------------------------------------------------
-- Table `steel_cbms`.`cust_account_assign_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`cust_account_assign_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `reg_time` DATETIME NOT NULL COMMENT '注册时间',
  `manager_ex_id` BIGINT NOT NULL COMMENT '前管理员ID',
  `manager_ex_name` VARCHAR(45) NOT NULL COMMENT '前管理员姓名',
  `manager_next_id` BIGINT NOT NULL COMMENT '现管理员ID',
  `manager_next_name` VARCHAR(45) NOT NULL COMMENT '现管理员姓名',
  `assigner_id` BIGINT NOT NULL COMMENT '分配人ID',
  `assigner_name` VARCHAR(45) NOT NULL COMMENT '分配人姓名',
  `type` ENUM('buyer','seller') NOT NULL DEFAULT 'buyer' COMMENT '分配类型 1.买家，2.卖家',
  `created` DATETIME NULL DEFAULT now(),
  `created_by` VARCHAR(45) NULL,
  `last_updated` DATETIME NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NULL,
  `modification_number` INT(20) NULL,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '客户公司划转日志';


-- -----------------------------------------------------
-- Table `steel_cbms`.`acl_user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`acl_user_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `permission_id` BIGINT NOT NULL COMMENT '权限ID',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `type` INT NOT NULL DEFAULT 1 COMMENT '操作类型 0减权限 1增权限',
  PRIMARY KEY (`id`))
  COMMENT = '用户特殊权限详情（结合角色权限一起使用）';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_consign_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_consign_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL COMMENT '单号',
  `account_id` BIGINT NOT NULL COMMENT '买家ID',
  `account_name` VARCHAR(45) NOT NULL COMMENT '买家企业名称',
  `owner_id` BIGINT NOT NULL COMMENT '交易员ID',
  `owner_name` VARCHAR(45) NOT NULL COMMENT '交易员姓名',
  `contact_id` BIGINT NOT NULL COMMENT '联系人ID',
  `contact_name` VARCHAR(45) NOT NULL COMMENT '联系人姓名',
  `contact_tel` VARCHAR(45) NOT NULL COMMENT '联系人电话',
  `delivery_type` ENUM('SELFPICK','DISPATCH') NOT NULL COMMENT 'SELFPICK：自提+DISPATCH:配送',
  `delivery_start_date` DATETIME NULL COMMENT '交货开始时间',
  `delivery_end_date` DATETIME NULL COMMENT '交货结束时间',
  `fee_taker` VARCHAR(45) NOT NULL COMMENT '费用承担方',
  `ship_fee` DECIMAL(18,6) NULL COMMENT '运费',
  `total_quantity` INT NOT NULL COMMENT '总件数',
  `total_weight` DECIMAL(18,6) NOT NULL COMMENT '总重量',
  `total_amount` DECIMAL(18,6) NOT NULL COMMENT '总金额',
  `status` VARCHAR(45) NOT NULL COMMENT '1 NEW 新建（待审核） 待审核\n-1 NEWDECLINED 订单关闭-审核不通过\n2 NEWAPPROVED 审核通过(待关联) 待关联\n3 CLOSEREQUEST1 请求关闭1\n-2 CLOSE1APPROVED 订单关闭-请求1通过\n4 RELATED 已关联\n5 CLOSEREQUEST2 请求关闭2\n-2 CLOSE2APPROVED 订单关闭-请求2通过\n6 SECONDSETTLE 待二次结算\n7 INVOICEREQUEST 待开票申请\n8 INVOICE 待开票\n10 FINISH 交易完成\n-3 SYSCLOSED 订单关闭-5点半未关联（待关联）订单',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `contract_code` VARCHAR(45) NULL COMMENT '采购合同号',
  `pay_status` VARCHAR(45) NOT NULL DEFAULT 'APPLY' COMMENT '付款状态\nAPPLY 待申请（未申请／审核不通过）\nREQUESTED 已申请/待审核\nAPPROVED 已通过审核待确认付款\nPAYED已确认付款',
  `pickup_status` INT NOT NULL DEFAULT 1 COMMENT '提货状态：\n1 未录入\n2 部分录入\n3 全录入',
  `fillup_status` INT NOT NULL DEFAULT 0 COMMENT '放货打印状态\n1　已全打印\n0　未全打印\n2    全匹配',
  `operator_id` BIGINT NOT NULL COMMENT '创建人Id',
  `operator_name` VARCHAR(45) NOT NULL COMMENT '创建人名称',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '代运营交易订单';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_consign_order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_consign_order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NULL COMMENT '订单号',
  `seller_id` BIGINT NULL COMMENT '卖家ID',
  `seller_name` VARCHAR(45) NULL COMMENT '卖家名称',
  `nsort_name` VARCHAR(45) NULL COMMENT '品名',
  `material` VARCHAR(45) NULL COMMENT '材质',
  `spec` VARCHAR(45) NULL COMMENT '规格',
  `factory` VARCHAR(45) NULL COMMENT '厂家',
  `city` VARCHAR(45) NULL COMMENT '城市',
  `warehouse` VARCHAR(45) NULL COMMENT '仓库',
  `quantity` INT NULL COMMENT '数量 件数',
  `weight` DECIMAL(18,6) NULL COMMENT '重量',
  `weight_concept` VARCHAR(45) NULL COMMENT '理计，磅计，抄码',
  `cost_price` DECIMAL(18,6) NULL COMMENT '底价',
  `deal_price` DECIMAL(18,6) NULL COMMENT '成交价',
  `amount` DECIMAL(18,6) NULL COMMENT '金额',
  `invoice_amount` DECIMAL(18,6) NULL COMMENT '已开票金额（可以一次开部分金额）',
  `actual_pick_weight_salesman` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '交易员录入的实际提货重量（用于二次结算）',
  `actual_pick_weight_server` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '内勤员录入的实际提货重量（用于二次结算）',
  `actual_pick_quantity_salesman` INT NOT NULL DEFAULT 0 COMMENT '交易员录入的实际提货件数（用于二次结算）',
  `actual_pick_quantity_server` INT NOT NULL DEFAULT 0 COMMENT '内勤员录入的实际提货件数（用于二次结算）',
  `status` INT NOT NULL DEFAULT 0 COMMENT '匹配状态\n0未匹配\n1已匹配',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  COMMENT = '代运营订单商品明细';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_pickup_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_pickup_bill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL COMMENT '提货单号',
  `consign_order_id` BIGINT NULL COMMENT '代运营单ID',
  `consign_order_code` VARCHAR(45) NOT NULL COMMENT '代运营单号',
  `buyer_id` BIGINT NOT NULL COMMENT '卖家ID',
  `buyer_name` VARCHAR(45) NOT NULL COMMENT '卖家全称',
  `delivery_type` VARCHAR(30) NOT NULL COMMENT '提货方式',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `total_weight` DECIMAL(18,6) NULL COMMENT '总重量',
  `total_quantity` INT NULL COMMENT '总数量',
  `total_amount` DECIMAL(18,6) NULL COMMENT '总金额',
  `print_times` INT NULL COMMENT '打印次数，大于0则为已打印',
  `buyer_pickupbill_path` VARCHAR(100) NULL COMMENT '买家提货单图片保存路径',
  `status` INT NOT NULL DEFAULT 1 COMMENT '状态\n1有效\n0无效',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '提货单';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_delivery_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_delivery_bill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL COMMENT '提货单号',
  `consign_order_id` BIGINT NULL COMMENT '代运营单ID',
  `consign_order_code` VARCHAR(45) NOT NULL COMMENT '代运营单号',
  `pickup_id` BIGINT NULL COMMENT '提货单ID',
  `pickup_code` VARCHAR(45) NULL COMMENT '提货单号',
  `buyer_id` BIGINT NOT NULL COMMENT '卖家ID',
  `buyer_name` VARCHAR(45) NOT NULL COMMENT '卖家全称',
  `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
  `seller_name` VARCHAR(45) NOT NULL COMMENT '卖家名称',
  `delivery_type` VARCHAR(30) NOT NULL COMMENT '提货方式',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `total_weight` DECIMAL(18,6) NULL COMMENT '总重量',
  `total_quantity` INT NULL COMMENT '总数量',
  `total_amount` DECIMAL(18,6) NULL COMMENT '总金额',
  `print_times` INT NULL COMMENT '打印次数，大于0则为已打印',
  `delivery_order_code` VARCHAR(45) NULL COMMENT '放货单编号',
  `delivery_order_print_times` INT NULL COMMENT '放货单打印次数',
  `buyer_pickupbill_path` VARCHAR(100) NULL COMMENT '买家提货单图片保存路径',
  `status` INT NOT NULL DEFAULT 1 COMMENT '状态\n1有效\n0无效',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '放货单';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_delivery_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_delivery_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `bill_id` BIGINT NULL COMMENT '放货单ID',
  `pickup_id` BIGINT NULL COMMENT '提货单ID',
  `consign_order_item_id` BIGINT NOT NULL COMMENT '代运营单明细ID',
  `picked_quantity` INT NOT NULL COMMENT '已提数量',
  `pick_quantity` INT NOT NULL COMMENT '提货数量',
  `pick_weight` DECIMAL(18,6) NOT NULL COMMENT '提货重量',
  `package_no` VARCHAR(45) NULL COMMENT '捆包号',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '放货单明细';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_pickup_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_pickup_person` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `valid_code` VARCHAR(45) NOT NULL COMMENT '证件号，如车牌号，身份证号',
  `pickup_bill_id` BIGINT NOT NULL COMMENT '提货单号',
  `name` VARCHAR(45) NOT NULL COMMENT '提货人姓名',
  `mobil` VARCHAR(45) NOT NULL COMMENT '联系方式',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '提货人';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_pickup_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_pickup_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pickup_bill_id` BIGINT NOT NULL COMMENT '提货单号',
  `file_url` VARCHAR(150) NOT NULL COMMENT '文件地址',
  `status` INT NOT NULL DEFAULT 1 COMMENT '状态\n1有效\n0无效',
  `note` VARCHAR(100) NULL COMMENT '备注，用于说明附件的用途',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '提货单附件';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_consign_order_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_consign_order_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consign_order_id` BIGINT NOT NULL COMMENT '订单号',
  `type` VARCHAR(30) NOT NULL COMMENT '类型，如 合同',
  `file_url` VARCHAR(150) NOT NULL COMMENT '附件路径',
  `relate_id` BIGINT NOT NULL DEFAULT 0 COMMENT '关联ID，如：代运营订单合同表ID',
  `status` INT NOT NULL DEFAULT 0 COMMENT '状态 \n0有效 默认\n1无效（逻辑删除）',
  `note` VARCHAR(100) NULL COMMENT '备注',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '代运营订单合同附件';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_bank_transaction_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_bank_transaction_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `transaction_number` VARCHAR(45) NOT NULL COMMENT '银行交易号',
  `serial_number` VARCHAR(45) NOT NULL COMMENT '银行流水号',
  `payee_bank_name` VARCHAR(45) NOT NULL COMMENT '付款银行',
  `payee_name` VARCHAR(60) NOT NULL COMMENT '客户名称',
  `payee_acctount_number` VARCHAR(45) NOT NULL COMMENT '银行账号',
  `transaction_amount` DECIMAL(18,6) NOT NULL COMMENT '到账金额',
  `transaction_time` DATETIME NOT NULL COMMENT '到账时间',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `is_related` BIT(1) NOT NULL DEFAULT 0 COMMENT '是否关联，周鹏2015/7/17 20:04这列不要了',
  `status` VARCHAR(30) NOT NULL COMMENT '状态 \n\nnormal  正常\n\nunprocessed 未处理\n\nrefund 已处理-退款\n\ncharge 已处理-充值',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '银行到账流水明细（用于到账异常处理及到账关联）';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_refund_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_refund_request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ref_bank_serial_number` VARCHAR(45) NOT NULL COMMENT '相关银行流水号',
  `type` VARCHAR(45) NOT NULL COMMENT '业务类型',
  `receiver_name` VARCHAR(45) NOT NULL COMMENT '收款单位',
  `receiver_account_name` VARCHAR(45) NOT NULL COMMENT '收款单位开户行',
  `receiver_account_code` VARCHAR(45) NOT NULL COMMENT '收款单位银行账号',
  `amount_upper_case` VARCHAR(45) NOT NULL COMMENT '金额大写',
  `amount_lower_case` DECIMAL(18,6) NOT NULL COMMENT '金额',
  `reason` VARCHAR(255) NULL COMMENT '原因',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '退款申请';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_consign_order_audit_trail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_consign_order_audit_trail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT NULL COMMENT '订单ID',
  `set_to_status` VARCHAR(45) NULL COMMENT '设置成状态',
  `operator_id` BIGINT NULL COMMENT '操作员ID，如果为空表示系统自动关闭',
  `operator_name` VARCHAR(45) NULL COMMENT '操作员姓名',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `status_type` ENUM('MAIN', 'PAY', 'SECONDPAY', 'PICKUP', 'FILLUP') NULL COMMENT '状态类别：\nMAIN 订单状态\nPAY 付款状态\nSECONDPAY 二次结算付款\nPICKUP 提货状态\nFILLUP  放货状态\n\n',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '代运营订单审核状态';


-- -----------------------------------------------------
-- Table `steel_cbms`.`acl_shiro_filter_chain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`acl_shiro_filter_chain` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(100) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  `type` VARCHAR(30) NULL,
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '系统初始化过滤配置信息';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_bank_transaction_original_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_bank_transaction_original_header` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `req_acctNo` VARCHAR(20) NULL COMMENT '账号',
  `req_beginDate` DATE NULL COMMENT '开始日期',
  `req_endDate` DATE NULL COMMENT '结束日期',
  `req_queryNumber` INT NULL COMMENT '查询的笔数',
  `req_beginNumber` INT NULL COMMENT '查询的起始笔数',
  `req_transAmount` DECIMAL(18,6) NULL COMMENT '交易金额',
  `req_subAccount` CHAR(32) NULL COMMENT '对方帐号',
  `req_subAcctName` CHAR(62) NULL COMMENT '对方户名',
  `res_totalCount` INT NULL COMMENT '交易总笔数',
  `res_acctNo` VARCHAR(20) NULL COMMENT '账号',
  `res_acctName` VARCHAR(60) NULL COMMENT '账号名称',
  `res_currency` INT(2) NULL COMMENT '账户币种',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '银企直联查询日志';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_bank_transaction_original_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_bank_transaction_original_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `header_id` BIGINT NOT NULL COMMENT '表头ID',
  `voucherNo` VARCHAR(13) NULL COMMENT '凭证号',
  `seqNo` VARCHAR(12) NULL COMMENT '交易流水号:记账流水',
  `txAmount` VARCHAR(18) NULL COMMENT '交易金额',
  `balance` VARCHAR(18) NULL COMMENT '账户余额',
  `tranFlag` VARCHAR(1) NULL COMMENT '借贷标志\n0：借\n1：贷\n',
  `transDate` VARCHAR(10) NULL COMMENT '交易日期',
  `transTime` VARCHAR(10) NULL COMMENT '交易时间\nHHMMSS，\n最长6位，最短只有1位\n',
  `note` VARCHAR(60) NULL COMMENT '备注 :客户附言',
  `remark` VARCHAR(22) NULL COMMENT '摘要代码',
  `payeeBankNo` VARCHAR(12) NULL COMMENT 'payeeBankNo',
  `payeeBankName` VARCHAR(62) NULL COMMENT '对方行名',
  `payeeAcctNo` VARCHAR(32) NULL COMMENT '对方账号',
  `payeeName` VARCHAR(60) NULL COMMENT '对方户名',
  `transCode` VARCHAR(4) NULL COMMENT '交易代码',
  `branchId` VARCHAR(4) NULL COMMENT '分行ID',
  `customerAcctNo` VARCHAR(20) NULL COMMENT '客户账号',
  `payeeAcctType` VARCHAR(1) NULL COMMENT '对方账号类型\n\n**KHZHLX        客户账号类型\n0-对公账号\n1-卡\n2-活期一本通\n3-定期一本通\n4-定期存折\n5-存单\n6-国债\n7-外系统账号\n8-活期存折\n9-内部帐/表外帐\nS-对私内部账号\nT-个人保证金\nU-浦发花旗信用卡卡号\nZ-客户号\n',
  `transCounter` VARCHAR(8) NULL COMMENT '交易柜员',
  `authCounter` VARCHAR(8) NULL COMMENT '授权柜员',
  `otherChar10` VARCHAR(10) NULL COMMENT '备用域10位',
  `otherChar40` VARCHAR(10) NULL COMMENT '备用域40位',
  `seqNum` VARCHAR(4) NULL COMMENT '传票序号:记账流水的序号',
  `revFlag` VARCHAR(1) NULL COMMENT '冲补标志\n0-无关\n1-当日抹帐\n2-隔日抹帐\n',
  `begin_number` INT NOT NULL DEFAULT 0 COMMENT '查询起始笔数',
  `begin_date` VARCHAR(30) NULL COMMENT '查询起始日期',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '银企直销银行流水记账明细';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_pay_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_pay_request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL COMMENT '付款申请单号',
  `consign_order_id` BIGINT NULL COMMENT '代运营单号 订单初次付款申请，二次结算时勾选申请付款这两种情况下使用,提现不需要',
  `consign_order_code` VARCHAR(45) NULL COMMENT '代运营单号 订单初次付款申请，二次结算时勾选申请付款这两种情况下使用,提现不需要',
  `contract_code` VARCHAR(45) NULL COMMENT '代运营单采购合同号 订单初次付款申请，二次结算时勾选申请付款这两种情况下使用,提现不需要',
  `contract_url` VARCHAR(100) NULL COMMENT '上传合同地址',
  `requester_id` BIGINT NULL COMMENT '申请人id',
  `requester_name` VARCHAR(45) NULL COMMENT '申请人姓名',
  `org_id` BIGINT NULL COMMENT '申请部门ID',
  `org_name` VARCHAR(45) NULL COMMENT '申请部门名称',
  `buyer_id` BIGINT NULL COMMENT '买家客户ID  订单初次付款申请，二次结算时勾选申请付款这两种情况下使用,提现不需要',
  `buyer_name` VARCHAR(45) NULL COMMENT '收款客户名称',
  `total_amount` DECIMAL(18,6) NULL COMMENT '付款总金额',
  `status` VARCHAR(45) NOT NULL COMMENT '状态\nREQUESTED 已申请 待审核\nAPPROVED 已通过审核\nDECLINED 未通过\nCONFIRMEDPAY 已确认付款',
  `decline_reason` VARCHAR(200) NULL COMMENT '未通过审核原因',
  `type` VARCHAR(45) NULL COMMENT '类型，\n1.初次付款\n2.二次结算\n3.提现',
  `print_times` INT NULL COMMENT '打印次数',
  `bank_id` BIGINT NOT NULL COMMENT '银行ID',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '付款申请单(一次,二次,提现)';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_bill_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_bill_sequence` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL COMMENT '用户ID',
  `org_id` BIGINT NOT NULL COMMENT '部门ID',
  `account_id` BIGINT NOT NULL COMMENT '客户ID',
  `seq_type` VARCHAR(45) NOT NULL COMMENT '类型\nJS 代运营订单\nDH 订货\nXS 销售\nJS-HZ-000001-1506-300',
  `current_value` INT NOT NULL COMMENT '当前值',
  `seq_date` VARCHAR(8) NULL COMMENT '序列年月 如 1504',
  `created` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_consign_process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_consign_process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL DEFAULT 0 COMMENT '组织机构ID',
  `org_name` VARCHAR(45) NOT NULL COMMENT '组织机构名称',
  `user_id` BIGINT NOT NULL DEFAULT 0 COMMENT '交易员ID',
  `user_name` VARCHAR(45) NOT NULL COMMENT '交易员名称',
  `order_status_code` VARCHAR(45) NOT NULL COMMENT '订单状态',
  `order_status_name` VARCHAR(45) NOT NULL,
  `operator_id` BIGINT NOT NULL DEFAULT 0 COMMENT '流程操作员ID',
  `operator_name` VARCHAR(45) NOT NULL COMMENT '流程操作员姓名',
  `operator_mobile` VARCHAR(45) NOT NULL COMMENT '流程操作员手机',
  `operator_role_name` VARCHAR(45) NOT NULL COMMENT '流程操作员角色',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  COMMENT = '代运营流程定义';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_pay_request_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_pay_request_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `request_id` BIGINT NULL COMMENT '申请单ID',
  `receiver_id` BIGINT NULL COMMENT '收款客户id',
  `receiver_name` VARCHAR(45) NULL COMMENT '收款单位',
  `receiver_bank_name` VARCHAR(45) NULL COMMENT '收款单位开户行',
  `receiver_bank_city` VARCHAR(45) NULL COMMENT '收款人银行所在城市',
  `receiver_branch_bank_name` VARCHAR(45) NULL,
  `receiver_account_code` VARCHAR(45) NULL COMMENT '收款银行账号',
  `receiver_tel` VARCHAR(45) NULL COMMENT '联系电话',
  `receiver_reg_addr` VARCHAR(45) NULL COMMENT '注册地址',
  `pay_amount` DECIMAL(18,6) NULL COMMENT '付款金额',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '付款申请明细表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_pickup_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_pickup_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `bill_id` BIGINT NULL COMMENT '提货单ID',
  `seller_id` BIGINT NULL,
  `seller_name` VARCHAR(45) NULL COMMENT '卖家名称',
  `consign_order_item_id` BIGINT NOT NULL COMMENT '代运营单明细ID',
  `picked_quantity` INT NOT NULL COMMENT '已提数量',
  `pick_quantity` INT NOT NULL COMMENT '提货数量',
  `pick_weight` DECIMAL(18,6) NOT NULL COMMENT '提货重量',
  `package_no` VARCHAR(45) NULL COMMENT '捆包号',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '提货单明细';


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_consign_order_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_consign_order_contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consign_order_id` BIGINT NOT NULL DEFAULT 0 COMMENT '代运营订单ID',
  `contract_code_auto` VARCHAR(45) NOT NULL COMMENT '合同编号（自动生成）',
  `contract_code_cust` VARCHAR(45) NULL COMMENT '合同编号（客户自定义）',
  `bank_name_main` VARCHAR(45) NOT NULL COMMENT '开户银行主行 如 工商银行',
  `bank_name_branch` VARCHAR(45) NULL COMMENT '开户银行支行 如XX支行',
  `bank_account_code` VARCHAR(45) NOT NULL COMMENT '银行账号',
  `customer_name` VARCHAR(45) NOT NULL COMMENT '客户单位名称',
  `customer_addr` VARCHAR(45) NULL COMMENT '客户单位注册地址',
  `customer_tel` VARCHAR(45) NOT NULL COMMENT '客户联系电话',
  `order_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '订单金额',
  `balance_second_settlement` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '二次结算记账余额',
  `apply_pay_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '申请付款金额',
  `status` VARCHAR(45) NOT NULL DEFAULT 0 COMMENT '状态\n0.未申请付款合同未上\n1.未申请付款合同已上传\n2.已申请付款',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  COMMENT = '代运营订单合同';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_in_owner_transition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_in_owner_transition` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_from_id` BIGINT NOT NULL COMMENT '所有权转出服务中心ID',
  `org_from_name` VARCHAR(45) NOT NULL COMMENT '所有权转出服务中心名称',
  `org_to_id` BIGINT NOT NULL COMMENT '所有权转入服务中心ID',
  `org_to_name` VARCHAR(45) NOT NULL COMMENT '所有权转入服务中心名称',
  `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
  `seller_name` VARCHAR(45) NOT NULL COMMENT '卖家名称',
  `nsort_name` VARCHAR(45) NOT NULL COMMENT '品名',
  `material` VARCHAR(45) NOT NULL COMMENT '材质',
  `spec` VARCHAR(45) NOT NULL COMMENT '规格',
  `not_invoiced_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '未开票金额 二次结算时增加，进项票进来时减少',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '二次结算进项票所有权转移表，跨服务中心交易时产生的进项票所有权';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_in_owner_transition_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_in_owner_transition_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_transition_id` BIGINT NOT NULL COMMENT '主表外键',
  `type` VARCHAR(45) NOT NULL COMMENT '数据来源类型,ORDER订单,INVOICE发票',
  `source_id` BIGINT NOT NULL COMMENT '来源票据明细ID，订单：busi_consign_order_item.id 进项票 inv_invoice_in_detail.id',
  `amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '金额',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_pool_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_pool_in` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL COMMENT '服务中心ID',
  `org_name` VARCHAR(45) NOT NULL COMMENT '服务中心名称',
  `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
  `seller_name` VARCHAR(45) NOT NULL COMMENT '卖家名称',
  `total_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '总金额',
  `total_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '总重量',
  `total_received_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已收总金额',
  `total_received_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已收总重量',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '进项池主表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_pool_in_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_pool_in_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pool_in_id` BIGINT NOT NULL,
  `nsort_name` VARCHAR(45) NOT NULL COMMENT '品名',
  `material` VARCHAR(45) NOT NULL COMMENT '材质',
  `spec` VARCHAR(45) NOT NULL COMMENT '规格',
  `total_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '总金额',
  `total_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '总重量',
  `received_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已收金额',
  `received_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已收重量',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '进项池明细表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_in` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL COMMENT '发票号',
  `org_id` BIGINT NOT NULL COMMENT '服务中心ID',
  `org_name` VARCHAR(45) NOT NULL COMMENT '服务中心名称',
  `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
  `seller_name` VARCHAR(45) NOT NULL COMMENT '卖家名称',
  `total_amount` DECIMAL(18,6) NOT NULL COMMENT '总金额',
  `total_weight` DECIMAL(18,6) NOT NULL COMMENT '总重量',
  `check_total_amount` DECIMAL(18,6) NOT NULL COMMENT '核实总金额',
  `check_total_weight` DECIMAL(18,6) NOT NULL COMMENT '核实总重量',
  `invoice_date` DATETIME NULL COMMENT '发票日期',
  `check_date` DATETIME NULL COMMENT '核算日期',
  `check_user_id` BIGINT NULL COMMENT '核实员ID',
  `check_user_name` VARCHAR(45) NULL COMMENT '核实人姓名',
  `check_user_mobil` VARCHAR(45) NULL COMMENT '核实员电话',
  `input_user_id` BIGINT NULL COMMENT '录入员ID',
  `input_user_name` VARCHAR(45) NULL COMMENT '录入人姓名',
  `input_user_mobil` VARCHAR(45) NULL COMMENT '录入员电话',
  `status` VARCHAR(45) NULL COMMENT '发票状态',
  `express_id` BIGINT NOT NULL DEFAULT 0 COMMENT '快递单ID',
  `print_status` VARCHAR(45) NULL COMMENT '打印状态',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '进项票主表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_in_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_in_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `invoice_in_id` BIGINT NOT NULL,
  `nsort_name` VARCHAR(45) NOT NULL COMMENT '品名',
  `material` VARCHAR(45) NOT NULL COMMENT '材质',
  `spec` VARCHAR(45) NOT NULL COMMENT '规格',
  `weight` DECIMAL(18,6) NOT NULL COMMENT '重量',
  `no_tax_amount` DECIMAL(18,6) NULL COMMENT '不含税金额',
  `tax_amount` DECIMAL(18,6) NULL COMMENT '税额',
  `amount` DECIMAL(18,6) NULL COMMENT '含税金额',
  `check_weight` DECIMAL(18,6) NULL COMMENT '核算重量',
  `check_no_tax_amount` DECIMAL(18,6) NULL COMMENT '核实发票无税金额',
  `check_tax_amount` DECIMAL(18,6) NULL COMMENT '核实发票税金',
  `check_amount` DECIMAL(18,6) NULL COMMENT '核算金额',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '进项票主表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_express`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_express` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(45) NOT NULL COMMENT '快递公司名称 顺丰,EMS,人肉（自己带）',
  `express_name` VARCHAR(45) NOT NULL COMMENT '快递单号，快递公司类型为人肉则是运送人姓名',
  `type` VARCHAR(45) NOT NULL COMMENT '类型 IN进项票OUT销项票',
  `send_time` DATETIME NULL COMMENT '寄出时间',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '快递单信息';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_pool` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL COMMENT '发票类型 IN进项票 OUT销项票(系统生成)',
  `invoice_code` VARCHAR(45) NOT NULL COMMENT '发票号',
  `org_id` BIGINT NOT NULL,
  `org_name` VARCHAR(45) NOT NULL COMMENT '归属服务中心',
  `sort_name` VARCHAR(45) NULL COMMENT '大类',
  `nsort_name` VARCHAR(45) NOT NULL COMMENT '品名',
  `material` VARCHAR(45) NOT NULL COMMENT '材质',
  `spec` VARCHAR(45) NOT NULL COMMENT '规格',
  `no_tax_amount` DECIMAL(18,6) NOT NULL COMMENT '不含税金额',
  `tax_amount` DECIMAL(18,6) NOT NULL COMMENT '税额',
  `amount` DECIMAL(18,6) NOT NULL COMMENT '含税金额',
  `weight` DECIMAL(18,6) NOT NULL COMMENT '重量',
  `invoice_date` DATETIME NOT NULL COMMENT '开票确认日期，注：这里的日期不是发票的开票日期，是确认日期，如果一张进项票开票时间是7月，确认日期是8月，算作8月的开票，此字段用于统计当月进销项票总额',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '发票池';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_out`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_out` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL COMMENT '销项票真实票号',
  `org_id` BIGINT NOT NULL COMMENT '服务中心ID',
  `org_name` VARCHAR(45) NOT NULL COMMENT '服务中心名称',
  `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
  `buyer_name` VARCHAR(45) NOT NULL COMMENT '买家名称',
  `amount` DECIMAL(18,6) NOT NULL COMMENT '发票金额',
  `check_amount` DECIMAL(18,6) NULL COMMENT '内勤核算录入金额',
  `check_user_id` BIGINT NULL COMMENT '核对内勤人员ID',
  `check_user_name` VARCHAR(45) NULL COMMENT '核对内勤人员姓名',
  `check_date` DATETIME NULL COMMENT '核对日期',
  `invoice_date` DATETIME NULL COMMENT '发票日期',
  `input_user_id` BIGINT NULL COMMENT '录入员ID',
  `input_user_name` VARCHAR(45) NULL COMMENT '录入人姓名',
  `input_user_mobil` VARCHAR(45) NULL COMMENT '录入员电话',
  `express_id` BIGINT NULL COMMENT '快递单外键',
  `status` VARCHAR(45) NULL COMMENT '发票状态 1待寄出 2 未确认 3确认通过 4确认失败',
  `print_status` VARCHAR(45) NULL COMMENT '打印状态',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '销项票主表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_invoice_out_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_invoice_out_apply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `owner_id` BIGINT NOT NULL COMMENT '交易员ID',
  `owner_name` VARCHAR(45) NOT NULL COMMENT '交易员姓名',
  `org_id` BIGINT NULL COMMENT '服务中心ID',
  `org_name` VARCHAR(45) NULL COMMENT '服务中心名称',
  `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
  `buyer_name` VARCHAR(45) NOT NULL COMMENT '买家名称',
  `is_independent` INT NOT NULL DEFAULT 0 COMMENT '是否单开0否1是',
  `apply_amount` DECIMAL(18,6) NULL COMMENT '申请金额',
  `actual_amount` DECIMAL(18,6) NULL COMMENT '实际开票金额',
  `status` VARCHAR(45) NULL COMMENT '1提交（待申请） 2总经理通过 3打回',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '销项发票申请表(交易员)';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_org_invoice_out_balance_monthly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_org_invoice_out_balance_monthly` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `month` VARCHAR(45) NULL COMMENT 'YYYYMM月份',
  `org_id` BIGINT NULL,
  `org_name` VARCHAR(45) NULL,
  `invoice_in_amount` DECIMAL(18,6) NULL COMMENT '当月进项金额',
  `invoice_out_amount` DECIMAL(18,6) NULL COMMENT '当月销项金额',
  `invoice_out_balance` DECIMAL(18,6) NULL COMMENT '历史可开销项票结余',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '服务中心每月销项票余额记录 每月定时job计算';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_org_invoice_out_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_org_invoice_out_apply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(18,6) NULL COMMENT '申请开票金额',
  `org_id` BIGINT NOT NULL COMMENT '服务中心ID',
  `org_name` VARCHAR(45) NOT NULL COMMENT '服务中心名称',
  `submitter_id` BIGINT NOT NULL COMMENT '提交人ID',
  `submitter_name` VARCHAR(45) NOT NULL COMMENT '提交人项目',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '服务中心开票申请';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_org_invoice_out_main`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_org_invoice_out_main` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_apply_id` BIGINT NULL,
  `code` VARCHAR(45) NULL COMMENT '系统生成发票编号',
  `real_code` VARCHAR(45) NULL COMMENT '真实销项发票号',
  `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
  `buyer_name` VARCHAR(45) NOT NULL COMMENT '买家名称',
  `total_no_tax_amount` DECIMAL(18,6) NULL COMMENT '总不含税金额',
  `total_tax_amount` DECIMAL(18,6) NULL COMMENT '总税额',
  `total_amount` DECIMAL(18,6) NOT NULL COMMENT '总金额',
  `total_weight` DECIMAL(18,6) NOT NULL COMMENT '总重量',
  `real_invoice_date` DATETIME NULL COMMENT '真实发票开票日期',
  `status` VARCHAR(45) NULL COMMENT '0财务未开票，1财务已开票',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '销项票发票号（系统生成）表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_org_invoice_out_item_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_org_invoice_out_item_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `invoice_out_main_id` BIGINT NOT NULL COMMENT '发票编号ID 外键',
  `nsort_name` VARCHAR(45) NOT NULL COMMENT '品名',
  `material` VARCHAR(45) NOT NULL COMMENT '材质',
  `spec` VARCHAR(45) NOT NULL COMMENT '规格',
  `weight` DECIMAL(18,6) NOT NULL COMMENT '重量',
  `price` DECIMAL(18,6) NOT NULL COMMENT '单价',
  `no_tax_amount` DECIMAL(18,6) NOT NULL COMMENT '不含税金额',
  `tax_amount` DECIMAL(18,6) NOT NULL COMMENT '税额',
  `amount` DECIMAL(18,6) NULL COMMENT '含税金额',
  `export_time` DATETIME NULL COMMENT '首次导出实际',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '开票计算结果（品规级）';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_org_invoice_out_order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_org_invoice_out_order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `item_detail_id` BIGINT NOT NULL COMMENT '外键 开票结果品规级主键',
  `order_item_id` BIGINT NOT NULL COMMENT '订单明细ID',
  `weight` DECIMAL(18,6) NOT NULL COMMENT '开票重量',
  `amount` DECIMAL(18,6) NOT NULL COMMENT '开票金额',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '开票计算结果(订单明细级)';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_pool_out`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_pool_out` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `org_id` BIGINT NOT NULL COMMENT '服务中心ID',
  `org_name` VARCHAR(45) NOT NULL COMMENT '服务中心名称',
  `owner_id` BIGINT NOT NULL COMMENT '交易员ID',
  `owner_name` VARCHAR(45) NOT NULL COMMENT '交易员姓名',
  `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
  `buyer_name` VARCHAR(45) NOT NULL COMMENT '买家名称',
  `total_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '总金额',
  `total_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '总重量',
  `total_sent_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已付总金额',
  `total_sent_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已付总重量',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '进项池主表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`inv_pool_out_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`inv_pool_out_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pool_out_id` BIGINT NOT NULL,
  `nsort_name` VARCHAR(45) NOT NULL COMMENT '品名',
  `material` VARCHAR(45) NOT NULL COMMENT '材质',
  `spec` VARCHAR(45) NOT NULL COMMENT '规格',
  `total_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '未开票总金额',
  `total_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '未开票总重量',
  `sent_amount` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已开票金额',
  `sent_weight` DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '已开票重量',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL,
  `parent_row_id` VARCHAR(45) NULL,
  `ext1` VARCHAR(20) NULL,
  `ext2` VARCHAR(45) NULL,
  `ext3` VARCHAR(255) NULL,
  `ext4` INT NULL,
  `ext5` INT NULL,
  `ext6` INT NULL,
  `ext7` DATETIME NULL,
  `ext8` BIGINT NULL,
  PRIMARY KEY (`id`))
  COMMENT = '进项池明细表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`common_category_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`common_category_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL COMMENT '全站唯一标识',
  `parent_uuid` VARCHAR(45) NOT NULL COMMENT '父级uuid',
  `name` VARCHAR(45) NOT NULL COMMENT '分组名称',
  `site_uuid` VARCHAR(45) NOT NULL COMMENT '分组对应的站点',
  `is_deleted` BIT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `common_category_group_site_idx` (`site_uuid` ASC))
  COMMENT = '品名分组，分组,  可以存在上下级关系(板材-热轧/冷轧)分组跟对应的站点关联起来（超市，CBMS）';


-- -----------------------------------------------------
-- Table `steel_cbms`.`common_category_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`common_category_materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_uuid` VARCHAR(45) NOT NULL COMMENT '关联的品类id',
  `materials_uuid` VARCHAR(45) NOT NULL COMMENT '关联的材质id',
  `is_deleted` BIT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `common_category_materials_category_idx` (`category_uuid` ASC),
  INDEX `common_category_materials_materials_idx` (`materials_uuid` ASC))
  COMMENT = '品类对应的材质列表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`common_category_norms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`common_category_norms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_uuid` VARCHAR(45) NOT NULL COMMENT '关联的品类ID',
  `norms_uuid` VARCHAR(45) NOT NULL COMMENT '关联的规格ID',
  `range` VARCHAR(1000) NOT NULL COMMENT '该规格的取值范围',
  `range_type` VARCHAR(45) NOT NULL COMMENT '范围计算类型\nInteger: range是以-号分隔的两个整数\nDecimal: range是以-号分隔的两个浮点数\nString: range是以,号分隔的字符串',
  `is_deleted` BIT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `common_category_norms_category_idx` (`category_uuid` ASC),
  INDEX `common_category_norms_norms_idx` (`norms_uuid` ASC))
  COMMENT = '品名对应的规格表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`common_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`common_materials` (
  `id` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL COMMENT '全站唯一标识',
  `name` VARCHAR(45) NOT NULL COMMENT '材质名称',
  `is_deleted` BIT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
  COMMENT = '钢铁材质表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`common_norms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`common_norms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL COMMENT '全站唯一标识',
  `name` VARCHAR(45) NOT NULL COMMENT '规格名称（长、宽、高...）',
  `unit` VARCHAR(45) NOT NULL COMMENT '衡量单位（毫米、厘米...）',
  `is_deleted` BIT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
  COMMENT = '规格表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`common_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`common_site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL COMMENT '全站唯一标识',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '站点名称',
  `is_deleted` BIT NULL DEFAULT NULL COMMENT '逻辑删除',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
  COMMENT = '平台站点表';


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_rebate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_rebate` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_UUID` VARCHAR(45) NULL DEFAULT NULL COMMENT '对应品类的UUID',
  `rebate_role` DECIMAL(20,2) NULL DEFAULT NULL COMMENT '返利（元/吨）',
  `rebate_status` VARCHAR(45) NULL DEFAULT NULL COMMENT '返利状态（0已取消，1正在生效，2下个月生效）',
  `effective_time` DATETIME NULL DEFAULT NULL COMMENT '返利生效日期',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `steel_cbms`.`base_reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`base_reward` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_UUID` VARCHAR(45) NULL DEFAULT NULL COMMENT '对应品类UUID',
  `seller_limit` DECIMAL NULL DEFAULT NULL COMMENT '卖家月代运营量上限（吨）',
  `reward_role` DECIMAL(20,2) NULL DEFAULT NULL COMMENT '单位提成（元/吨）',
  `reward_status` VARCHAR(45) NULL DEFAULT NULL COMMENT '提成规则状态(0已失效，1正在生效，2下月生效)',
  `effective_time` DATETIME NULL DEFAULT NULL COMMENT '提成生效日期',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `steel_cbms`.`busi_print_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steel_cbms`.`busi_print_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `bill_code` VARCHAR(45) NOT NULL COMMENT '打印单据代号或编号',
  `bill_type` VARCHAR(45) NOT NULL COMMENT '打印单据类型',
  `user_id` BIGINT NOT NULL COMMENT '打印人ID',
  `user_name` VARCHAR(45) NOT NULL COMMENT '打印人名称',
  `ip_address` VARCHAR(45) NOT NULL COMMENT 'IP地址',
  `created` DATETIME NOT NULL DEFAULT now(),
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT now(),
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  `row_id` VARCHAR(45) NULL DEFAULT NULL,
  `parent_row_id` VARCHAR(45) NULL DEFAULT NULL,
  `ext1` VARCHAR(20) NULL DEFAULT NULL,
  `ext2` VARCHAR(45) NULL DEFAULT NULL,
  `ext3` VARCHAR(255) NULL DEFAULT NULL,
  `ext4` INT NULL DEFAULT NULL,
  `ext5` INT NULL DEFAULT NULL,
  `ext6` INT NULL DEFAULT NULL,
  `ext7` DATETIME NULL DEFAULT NULL,
  `ext8` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
COMMENT = '打印日志';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

