CREATE TABLE IF NOT EXISTS pyramid_db_version(version VARCHAR(100))ENGINE=InnoDB DEFAULT CHARSET=utf8; 
/* ***********************************
Version: 1
Added by: gelinzhong
Added at: 2016-04-26 17:16:55
Description: 初始化sql
************************************ */
-- MySQL Script generated by MySQL Workbench
-- 05/05/16 21:04:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ec2.0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ec2.0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ec2.0` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ec2.0` ;

-- -----------------------------------------------------
-- Table `ec2.0`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(20) NULL COMMENT '姓名',
  `mobile` VARCHAR(11) NOT NULL COMMENT '手机号',
  `source` VARCHAR(10) NULL COMMENT '用户来源 CBMS，MARKET，APP',
  `status` CHAR(1) NOT NULL DEFAULT '1' COMMENT '状态 0禁用 1启用',
  `remark` VARCHAR(255) NULL COMMENT '备注',
  `is_deleted` CHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `ec2.0`.`base_system_operation_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`base_system_operation_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `operator_guid` VARCHAR(45) NOT NULL COMMENT '操作者ID',
  `operator_name` VARCHAR(45) NOT NULL COMMENT '操作者姓名',
  `operation_key` VARCHAR(100) NOT NULL COMMENT '操作类型的key',
  `operation_name` VARCHAR(100) NOT NULL COMMENT '操作名称',
  `operation_level` VARCHAR(100) NOT NULL COMMENT '操作级别：Safe,Warning,Dangerous,Damning',
  `operation_level_value` INT(11) NULL COMMENT '操作等级的数字值，值越高表示越危险，用于按危险等级排序',
  `parameters` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '提交的参数',
  `remark` VARCHAR(255) NULL,
  `is_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
ENGINE = InnoDB
COMMENT = '系统操作日志';


-- -----------------------------------------------------
-- Table `ec2.0`.`busi_requirement_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`busi_requirement_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `requirement_guid` VARCHAR(45) NOT NULL COMMENT '需求主表',
  `category_uuid` VARCHAR(45) NOT NULL COMMENT '品名',
  `category_name` VARCHAR(45) NOT NULL,
  `material_uuid` VARCHAR(45) NOT NULL COMMENT '材质',
  `material_name` VARCHAR(45) NOT NULL,
  `spec1` VARCHAR(45) NOT NULL COMMENT '规格1',
  `spec2` VARCHAR(45) NULL,
  `spec3` VARCHAR(45) NULL,
  `factory_id` INT UNSIGNED NOT NULL COMMENT '厂家，钢厂',
  `factory_name` VARCHAR(45) NOT NULL,
  `city_id` INT UNSIGNED NOT NULL COMMENT '城市',
  `city_name` VARCHAR(60) NOT NULL,
  `price` DECIMAL(18,6) NULL,
  `weight` DECIMAL(18,6) NULL,
  `amount` DECIMAL(18,6) NULL,
  `weight_concept` VARCHAR(45) NULL,
  `remark` VARCHAR(255) NULL,
  `is_deleted` VARCHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '采购需求明细表，购物车使用';


-- -----------------------------------------------------
-- Table `ec2.0`.`busi_requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`busi_requirement` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL COMMENT '需求单号',
  `user_guid` VARCHAR(45) NOT NULL,
  `request` VARCHAR(255) NULL COMMENT '我的要求',
  `file_url` VARCHAR(500) NULL COMMENT '采购清单文件地址,多文件时逗号隔开',
  `source` VARCHAR(45) NOT NULL COMMENT '需求来源APP，WEB网站\n',
  `type` VARCHAR(30) NULL COMMENT '帮您找HELP，购物车CART,回执RECEIPT，再来一单ONEMORE,图片IMAGE',
  `stage_status` VARCHAR(30) NOT NULL DEFAULT 'NEW' COMMENT '状态，其他系统回写 NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价  --CLOSED已关闭',
  `close_stage` VARCHAR(45) NULL COMMENT '关闭阶段 PICKUP-分拣阶段 INQUERY--询价阶段 --BILL开出订单',
  `close_reason` VARCHAR(255) NULL COMMENT '关闭理由 ',
  `remark` VARCHAR(255) NULL,
  `is_deleted` CHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '采购需求主表';


-- -----------------------------------------------------
-- Table `ec2.0`.`mkt_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`mkt_cart` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `cookie_id` VARCHAR(45) NULL,
  `user_guid` VARCHAR(45) NULL COMMENT '用户',
  `seller_id` INT NULL COMMENT '卖家',
  `seller_name` VARCHAR(45) NULL,
  `category_uuid` VARCHAR(45) NOT NULL COMMENT '品名',
  `category_name` VARCHAR(45) NOT NULL,
  `material_uuid` VARCHAR(45) NOT NULL COMMENT '材质',
  `material_name` VARCHAR(45) NOT NULL,
  `spec1` VARCHAR(45) NULL COMMENT '规格1',
  `spec2` VARCHAR(45) NULL COMMENT '规格2',
  `spec3` VARCHAR(45) NULL COMMENT '规格3',
  `factory_id` INT UNSIGNED NOT NULL COMMENT '钢厂',
  `factory_name` VARCHAR(45) NOT NULL,
  `city_id` INT UNSIGNED NOT NULL COMMENT '城市',
  `city_name` VARCHAR(60) NOT NULL,
  `price` DECIMAL(18,6) NULL COMMENT '价格',
  `weight` DECIMAL(18,6) NOT NULL COMMENT '采购重量',
  `amount` DECIMAL(18,6) NULL COMMENT '金额',
  `weight_concept` VARCHAR(45) NOT NULL,
  `remark` VARCHAR(255) NULL,
  `is_checked` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '是否选中（待提交） 选中Y未选中N',
  `is_deleted` CHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '购物车';


-- -----------------------------------------------------
-- Table `ec2.0`.`mkt_search_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`mkt_search_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `cookie_id` VARCHAR(45) NULL,
  `user_guid` VARCHAR(45) NULL,
  `category_uuid` VARCHAR(45) NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `material_uuid` VARCHAR(255) NOT NULL COMMENT '材质，可多选，逗号隔开',
  `material_name` VARCHAR(255) NULL,
  `spec1` VARCHAR(255) NULL COMMENT '规格可多选',
  `spec2` VARCHAR(255) NULL COMMENT '单选或区间',
  `spec3` VARCHAR(255) NULL COMMENT '单选或区间',
  `factory_id` VARCHAR(255) NULL COMMENT '钢厂，多选，逗号隔开',
  `factory_name` VARCHAR(255) NULL,
  `city_id` VARCHAR(45) NULL COMMENT '城市id，多选，逗号隔开',
  `city_name` VARCHAR(255) NULL,
  `is_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `is_deleted_for_preference` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '是否参与猜你喜欢的统计运算',
  `remark` VARCHAR(255) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '搜索历史';


-- -----------------------------------------------------
-- Table `ec2.0`.`base_sms_valid_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`base_sms_valid_code` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `module` VARCHAR(45) NOT NULL COMMENT '使用的模块 REGISTER注册 LOGIN登录 CHANGEMOBILE改手机 ADDREQUIREMENT提需求 CHANGEPWD改密码',
  `mobile` VARCHAR(11) NOT NULL COMMENT '接收手机号',
  `valid_code` VARCHAR(45) NOT NULL COMMENT '验证码',
  `resend_time` DATETIME NULL COMMENT '再次发送时间 一般为发送后的60s',
  `expire_time` DATETIME NULL COMMENT '验证码失效时间一般为发送后的半小时',
  `remark` VARCHAR(255) NULL,
  `is_deleted` CHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '短信验证码';


-- -----------------------------------------------------
-- Table `ec2.0`.`mkt_search_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`mkt_search_preference` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `user_guid` VARCHAR(45) NULL,
  `category_uuid` VARCHAR(45) NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `material_uuid` VARCHAR(255) NOT NULL COMMENT '材质，可多选，逗号隔开',
  `material_name` VARCHAR(255) NULL,
  `spec1` VARCHAR(255) NULL COMMENT '规格可多选',
  `spec2` VARCHAR(255) NULL COMMENT '单选或区间',
  `spec3` VARCHAR(255) NULL COMMENT '单选或区间',
  `factory_id` VARCHAR(255) NULL COMMENT '钢厂，多选，逗号隔开',
  `factory_name` VARCHAR(255) NULL,
  `city_id` VARCHAR(45) NULL COMMENT '城市id，多选，逗号隔开',
  `city_name` VARCHAR(255) NULL,
  `count` INT UNSIGNED NULL DEFAULT 1 COMMENT '搜索次数',
  `is_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记 N未删除 Y删除',
  `remark` VARCHAR(255) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '搜索偏好表';


-- -----------------------------------------------------
-- Table `ec2.0`.`user_subscrib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`user_subscrib` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `user_guid` VARCHAR(45) NOT NULL COMMENT '用户ID',
  `category_uuid` VARCHAR(45) NULL COMMENT '订阅品名',
  `category_name` VARCHAR(45) NULL COMMENT '订阅品名名称',
  `note` VARCHAR(45) NULL,
  `remark` VARCHAR(255) NULL COMMENT '备注',
  `is_deleted` CHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '用户订阅表';


-- -----------------------------------------------------
-- Table `ec2.0`.`base_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`base_feedback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(45) NOT NULL,
  `user_guid` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `remark` VARCHAR(255) NULL,
  `is_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记 N未删除Y删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
COMMENT = '反馈表，app使用';


-- -----------------------------------------------------
-- Table `ec2.0`.`global_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`global_id` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
COMMENT = '全局唯一顺序号表';


-- -----------------------------------------------------
-- Table `ec2.0`.`busi_requirement_status_change_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ec2.0`.`busi_requirement_status_change_record` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `guid` VARCHAR(45) NOT NULL COMMENT 'guid',
  `user_guid` VARCHAR(45) NOT NULL COMMENT '用户guid',
  `requirement_guid` VARCHAR(45) NOT NULL COMMENT '需求单guid',
  `requirement_code` VARCHAR(45) NOT NULL COMMENT '需求单号',
  `remote_order_code` VARCHAR(45) NOT NULL COMMENT '外部系统单号(采购单、报价单)',
  `remote_order_created` DATETIME NOT NULL COMMENT '外部系统订单(采购单、报价单)创建时间',
  `origin_status` VARCHAR(11) NULL DEFAULT NULL COMMENT '原状态码：NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价  --FINISHED已完成  --CLOSED已关闭',
  `change_to_status` VARCHAR(11) NOT NULL COMMENT '新状态码：同上',
  `source` VARCHAR(11) NOT NULL COMMENT '数据来源：APP，EC超市，PICK分拣系统，SMART智能找货，CBMS寄售管理系统',
  `remark` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注',
  `is_deleted` CHAR(1) NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(45) NOT NULL,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` VARCHAR(45) NOT NULL,
  `modification_number` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '需求单状态变化记录表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/* ***********************************
Version: 3
Added by: gelinzhong
Added at: 2016-04-30 07:45:01
Description: 购物车补两个卖家字段
************************************ */
ALTER TABLE `mkt_cart`
ADD COLUMN `seller_id`  int NULL AFTER `user_guid`,
ADD COLUMN `seller_name`  varchar(45) NULL AFTER `seller_id`,
ADD COLUMN `is_checked`  char(1) NULL AFTER `remark`;

/* ***********************************
Version: 4
Added by: gelinzhong
Added at: 2016-04-30 07:47:52
Description: 添加demo表
************************************ */
-- ----------------------------
-- Table structure for `demo`
-- ----------------------------
DROP TABLE IF EXISTS `demo`;
CREATE TABLE `demo` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) DEFAULT NULL,
  `account` varchar(16) NOT NULL,
  `password` varchar(64) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `last_updated` datetime DEFAULT NULL,
  `last_updated_by` varchar(45) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `is_deleted` char(1) DEFAULT '0',
  `modification_number` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


/* ***********************************
Version: 5
Added by: gelinzhong
Added at: 2016-05-05 10:51:59
Description: 去掉购物车表的金额非空，考虑“议价”场景
************************************ */
ALTER TABLE `mkt_cart`
MODIFY COLUMN `amount`  decimal(18,6) NULL COMMENT '金额' AFTER `weight`;


/* ***********************************
Version: 6
Added by: maoyehui
Added at: 2016-05-06 07:04:08
Description: 需求单状态变化记录表
************************************ */
-- ----------------------------
-- Table structure for busi_requirement_status_change_record
-- ----------------------------
DROP TABLE IF EXISTS `busi_requirement_status_change_record`;
CREATE TABLE `busi_requirement_status_change_record` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `guid` varchar(45) NOT NULL COMMENT 'guid',
  `user_guid` varchar(45) NOT NULL COMMENT '用户guid',
  `requirement_guid` varchar(45) NOT NULL COMMENT '需求单guid',
  `requirement_code` varchar(45) NOT NULL COMMENT '需求单号',
  `remote_order_code` varchar(45) NOT NULL COMMENT '外部系统单号(采购单、报价单)',
  `remote_order_created` datetime NOT NULL COMMENT '外部系统订单(采购单、报价单)创建时间',
  `origin_status` varchar(11) DEFAULT NULL COMMENT '原状态码：NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价  --FINISHED已完成  --CLOSED已关闭',
  `change_to_status` varchar(11) NOT NULL COMMENT '新状态码：同上',
  `source` varchar(11) NOT NULL COMMENT '数据来源：APP，WEB超市，PICK分拣系统，SMART智能找货，CBMS寄售管理系统',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_deleted` char(1) DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='需求单状态变化记录表'

/* ***********************************
Version: 7
Added by: wangyixiao
Added at: 2016-05-06 08:14:32
Description: 需求表，状态和关闭阶段描述修改
************************************ */
ALTER TABLE `busi_requirement`
MODIFY COLUMN `stage_status`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'NEW' COMMENT '状态，其他系统回写 NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价 --FINISHED --已完成 --CLOSED已关闭' AFTER `type`,
MODIFY COLUMN `close_stage`  varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '关闭阶段 PICKUP-分拣阶段 INQUERY--询价阶段 QUOTED--报价阶段 ' AFTER `stage_status`;

/* ***********************************
Version: 8
Added by: gelinzhong
Added at: 2016-05-06 20:41:29
Description: cas_db init
************************************ */
/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50626
Source Host           : localhost:3306
Source Database       : cas

Target Server Type    : MYSQL
Target Server Version : 50626
File Encoding         : 65001

Date: 2016-04-30 17:05:26
*/

SET FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema cas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cas_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cas_db` ;

-- ----------------------------
-- Table structure for `user`
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(45) NOT NULL COMMENT '手机号',
  `password` varchar(100) DEFAULT NULL COMMENT '密码',
  `dynamic_password` varchar(100) DEFAULT NULL COMMENT '动态密码',
  `dynamic_password_expired` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '动态密码过期时间',
  `is_activated` char(1) NOT NULL DEFAULT 'N' COMMENT '是否已激活 N 未激活; Y 已激活 ',
  `is_locked` char(1) NOT NULL DEFAULT 'N' COMMENT '是否锁定 N 未锁定; Y 已锁定 ',
  `is_deleted` char(1) NOT NULL DEFAULT 'N' COMMENT '是否删除 N 未删除; Y 已删除 ',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_account` (`account`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('1', 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', '7c4a8d09ca3762af61e59520943dc26494f8941b', '2017-04-30 17:01:02', 'Y', 'N', 'N', '2016-04-30 17:01:02', '2016-04-30 17:01:02');

/* ***********************************
Version: 9
Added by: maoyehui
Added at: 2016-05-10 07:37:37
Description: 待办事项模拟数据sql，本sql会清空原数据！！！
************************************ */
/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : ec2.0

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2016-05-09 10:20:06
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for busi_requirement
-- ----------------------------
DROP TABLE IF EXISTS `busi_requirement`;
CREATE TABLE `busi_requirement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) NOT NULL,
  `code` varchar(45) DEFAULT NULL COMMENT '需求单号',
  `user_guid` varchar(45) NOT NULL,
  `request` varchar(255) DEFAULT NULL COMMENT '我的要求',
  `file_url` varchar(500) DEFAULT NULL COMMENT '采购清单文件地址,多文件时逗号隔开',
  `source` varchar(45) NOT NULL COMMENT '需求来源APP，WEB网站\n',
  `type` varchar(30) DEFAULT NULL COMMENT '帮您找HELP，购物车CART',
  `stage_status` varchar(30) NOT NULL DEFAULT 'NEW' COMMENT '状态，其他系统回写 NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价  --CLOSED已关闭',
  `close_stage` varchar(45) DEFAULT NULL COMMENT '关闭阶段 PICKUP-分拣阶段 INQUERY--询价阶段 --BILL开出订单',
  `close_reason` varchar(255) DEFAULT NULL COMMENT '关闭理由 ',
  `remark` varchar(255) DEFAULT NULL,
  `is_deleted` char(1) DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='采购需求主表';

-- ----------------------------
-- Records of busi_requirement
-- ----------------------------
INSERT INTO `busi_requirement` VALUES ('1', 'GUID_000000000G', '20160503-000007', '13500000002', null, null, 'WEB', 'CART', 'NEW', null, null, null, 'N', '2016-05-05 19:36:00', 'cbadmin', '2016-05-03 11:59:42', 'cbadmin', '0');
INSERT INTO `busi_requirement` VALUES ('2', 'GUID_000000001Q', 'CS102640_07120301', '13500000001', '我要一头会飞的猪', 'url1,url2', 'WEB', 'HELP', 'CLOSED', 'QUOTED', '猪飞不起来，我要退货', null, 'N', '2016-05-05 17:40:10', '1', '2016-05-05 21:18:52', '1', '0');
INSERT INTO `busi_requirement` VALUES ('3', 'GUID_000000000W', '20160503-000008', '13500000002', '我要一头会飞的猪', 'url1,url2', 'WEB', 'HELP', 'NEW', '', '', '', 'N', '2016-05-05 19:36:02', '1', '2016-05-05 21:21:13', '1', '0');
INSERT INTO `busi_requirement` VALUES ('4', 'GUID_000000000E', '20160503-000009', '13500000002', '', 'url1,url2', 'APP', 'IMAGE', 'NEW', '', '', '', 'N', '2016-05-05 19:36:04', '1', '2016-05-05 21:21:13', '1', '0');
INSERT INTO `busi_requirement` VALUES ('5', 'GUID_000000000R', '20160503-000010', '13500000002', '', '', 'APP', 'RECEIPT', 'NEW', '', '', '', 'N', '2016-05-05 19:36:06', '1', '2016-05-05 21:21:13', '1', '0');

-- ----------------------------
-- Table structure for busi_requirement_item
-- ----------------------------
DROP TABLE IF EXISTS `busi_requirement_item`;
CREATE TABLE `busi_requirement_item` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) NOT NULL,
  `requirement_guid` varchar(45) NOT NULL COMMENT '需求主表',
  `category_uuid` varchar(45) NOT NULL COMMENT '品名',
  `category_name` varchar(45) NOT NULL,
  `material_uuid` varchar(45) NOT NULL COMMENT '材质',
  `material_name` varchar(45) NOT NULL,
  `spec1` varchar(45) NOT NULL COMMENT '规格1',
  `spec2` varchar(45) DEFAULT NULL,
  `spec3` varchar(45) DEFAULT NULL,
  `factory_id` int(10) unsigned NOT NULL COMMENT '厂家，钢厂',
  `factory_name` varchar(45) NOT NULL,
  `city_id` int(10) unsigned NOT NULL COMMENT '城市',
  `city_name` varchar(60) NOT NULL,
  `price` decimal(18,6) DEFAULT NULL,
  `weight` decimal(18,6) DEFAULT NULL,
  `amount` decimal(18,6) DEFAULT NULL,
  `weight_concept` varchar(45) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `is_deleted` varchar(1) DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='采购需求明细表，购物车使用';

-- ----------------------------
-- Records of busi_requirement_item
-- ----------------------------
INSERT INTO `busi_requirement_item` VALUES ('1', 'GUID_000000000H', 'GUID_000000000G', 'category_uuid', '中厚板', 'material_uuid', 'B235', '4', '5', '6', '1', '湘钢', '1', '杭州', '3000.000000', '8.000000', '24000.000000', '1', null, 'N', '2016-05-03 11:59:42', 'cbadmin', '2016-05-03 11:59:42', 'cbadmin', '0');

-- ----------------------------
-- Table structure for busi_requirement_status_change_record
-- ----------------------------
DROP TABLE IF EXISTS `busi_requirement_status_change_record`;
CREATE TABLE `busi_requirement_status_change_record` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `guid` varchar(45) NOT NULL COMMENT 'guid',
  `user_guid` varchar(45) NOT NULL COMMENT '用户guid',
  `requirement_guid` varchar(45) NOT NULL COMMENT '需求单guid',
  `requirement_code` varchar(45) NOT NULL COMMENT '需求单号',
  `remote_order_code` varchar(45) NOT NULL COMMENT '外部系统单号(采购单、报价单)',
  `remote_order_created` datetime NOT NULL COMMENT '外部系统订单(采购单、报价单)创建时间',
  `origin_status` varchar(11) DEFAULT NULL COMMENT '原状态码：NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价  --FINISHED已完成  --CLOSED已关闭',
  `change_to_status` varchar(11) NOT NULL COMMENT '新状态码：同上',
  `source` varchar(11) NOT NULL COMMENT '数据来源：APP，WEB超市，PICK分拣系统，SMART智能找货，CBMS寄售管理系统',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_deleted` char(1) DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='需求单状态变化记录表';

-- ----------------------------
-- Records of busi_requirement_status_change_record
-- ----------------------------
INSERT INTO `busi_requirement_status_change_record` VALUES ('1', 'GUID_000000001Q', '13500000001', 'GUID_000000001Q', 'CS102640_07120301', 'CS102640_07120301', '2016-05-05 17:40:10', null, 'NEW', 'WEB', null, 'N', '2016-05-05 17:40:10', 'system', '2016-05-05 17:40:10', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('2', 'GUID_000000001W', '13500000001', 'GUID_000000001Q', 'CS102640_07120301', 'PICK102640_07120301', '2016-05-05 17:42:35', 'NEW', 'PICKED', 'PICK', null, 'N', '2016-05-05 17:42:41', 'system', '2016-05-05 17:42:41', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('3', 'GUID_000000001E', '13500000001', 'GUID_000000001Q', 'CS102640_07120301', 'SM102640_07120301', '2016-05-05 17:46:21', 'PICKED', 'QUOTED', 'SMART', null, 'N', '2016-05-05 17:46:41', 'system', '2016-05-05 17:46:41', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('4', 'GUID_000000001R', '13500000001', 'GUID_000000001Q', 'CS102640_07120301', 'SM102640_07120302', '2016-05-05 17:48:02', 'QUOTED', 'QUOTED', 'SMART', null, 'N', '2016-05-05 17:48:06', 'system', '2016-05-05 17:48:06', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('5', 'GUID_000000001T', '13500000001', 'GUID_000000001Q', 'CS102640_07120301', 'SM102640_07120302', '2016-05-05 17:49:59', 'QUOTED', 'FINISHED', 'SMART', null, 'N', '2016-05-05 17:50:01', 'system', '2016-05-05 17:50:01', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('6', 'GUID_000000001Y', '13500000001', 'GUID_000000001Q', 'CS102640_07120301', 'SM102640_07120302', '2016-05-05 19:26:16', 'FINISHED', 'CLOSED', 'SMART', null, 'N', '2016-05-05 19:26:19', 'system', '2016-05-05 19:26:19', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('7', 'GUID_000000000U', '13500000002', 'GUID_000000000G', '20160503-000007', '20160503-000007', '2016-05-05 19:36:00', null, 'NEW', 'WEB', null, 'N', '2016-05-05 19:36:00', 'system', '2016-05-05 19:36:00', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('8', 'GUID_000000000I', '13500000002', 'GUID_000000000W', '20160503-000008', '20160503-000008', '2016-05-05 19:36:02', '', 'NEW', 'WEB', '', 'N', '2016-05-05 19:36:00', 'system', '2016-05-05 19:36:00', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('9', 'GUID_000000000O', '13500000002', 'GUID_000000000E', '20160503-000009', '20160503-000009', '2016-05-05 19:36:04', '', 'NEW', 'APP', '', 'N', '2016-05-05 19:36:00', 'system', '2016-05-05 19:36:00', 'system', '0');
INSERT INTO `busi_requirement_status_change_record` VALUES ('10', 'GUID_000000000P', '13500000002', 'GUID_000000000R', '20160503-000010', '20160503-000010', '2016-05-05 19:36:06', '', 'NEW', 'APP', '', 'N', '2016-05-05 19:36:00', 'system', '2016-05-05 19:36:00', 'system', '0');

-- ----------------------------
-- Table structure for temp_requirement_dto
-- ----------------------------
DROP TABLE IF EXISTS `temp_requirement_dto`;
CREATE TABLE `temp_requirement_dto` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) NOT NULL,
  `code` varchar(45) NOT NULL,
  `remote_code` varchar(45) DEFAULT NULL COMMENT '外部系统单号',
  `request` varchar(255) DEFAULT NULL COMMENT '我的要求',
  `file_url` varchar(500) DEFAULT NULL COMMENT '采购清单文件地址,多文件时逗号隔开',
  `source` varchar(45) DEFAULT NULL COMMENT '需求来源APP，WEB网站\n',
  `type` varchar(30) DEFAULT NULL COMMENT '帮您找HELP，购物车CART',
  `stage_status` varchar(30) DEFAULT 'NEW' COMMENT '状态，其他系统回写 NEW -新建（待确认）  PICKED -分拣完成(待报价,报价中) - QUOTED --已报价  --CLOSED已关闭',
  `close_stage` varchar(45) DEFAULT NULL COMMENT '关闭阶段 PICKUP-分拣阶段 INQUERY--询价阶段 --BILL开出订单',
  `close_reason` varchar(255) DEFAULT NULL COMMENT '关闭理由 ',
  `city` varchar(255) DEFAULT NULL COMMENT '交货地',
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `operator` varchar(45) DEFAULT NULL,
  `mobile` varchar(45) DEFAULT NULL,
  `title` varchar(45) DEFAULT NULL,
  `author` varchar(45) DEFAULT NULL,
  `text` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `thumbnail` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='待办事项主表';

-- ----------------------------
-- Records of temp_requirement_dto
-- ----------------------------
INSERT INTO `temp_requirement_dto` VALUES ('1', 'GUID_000000000G', 'CS102640_07120301', 'PICK102640_07120301', null, null, 'PICK', null, null, null, null, '浙江杭州', '2016-05-05 17:42:35', '张三', '18767110989', null, null, null, null, null);
INSERT INTO `temp_requirement_dto` VALUES ('2', 'GUID_000000001Q', 'CS102640_07120301', 'SM102640_07120301', null, null, 'SMART', null, null, null, null, '浙江杭州', '2016-05-05 17:46:21', '张三', '18767110989', null, null, null, null, null);
INSERT INTO `temp_requirement_dto` VALUES ('3', 'GUID_000000000W', 'CS102640_07120301', 'SM102640_07120302', null, null, 'SMART', null, null, null, null, '浙江杭州', '2016-05-05 17:48:02', '张三', '18767110989', null, null, null, null, null);
INSERT INTO `temp_requirement_dto` VALUES ('4', 'GUID_000000001E', 'AN20301', null, null, null, null, 'MARKETANALYSIS', null, null, null, null, '2016-05-05 17:45:22', null, null, '【钢铁周报第13期】下周钢价延续弱势整理走势（3.25）', '孟城祥', '一、【本周国内钢价走势】：本周国内钢材价格先扬后抑，整体再度拉涨，不过受到月底资金回笼压力及成交跟进不足影响，临近周末涨势渐缓，部分地区、品类甚至有30~80元/吨不等的回调。', 'www.baidu.com', '缩略图url');

-- ----------------------------
-- Table structure for temp_requirement_item_dto
-- ----------------------------
DROP TABLE IF EXISTS `temp_requirement_item_dto`;
CREATE TABLE `temp_requirement_item_dto` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) NOT NULL,
  `remote_code` varchar(45) NOT NULL COMMENT '需求主表',
  `category_uuid` varchar(45) DEFAULT NULL COMMENT '品名',
  `category_name` varchar(45) DEFAULT NULL,
  `material_uuid` varchar(45) DEFAULT NULL COMMENT '材质',
  `material_name` varchar(45) DEFAULT NULL,
  `spec1` varchar(45) DEFAULT NULL COMMENT '规格1',
  `spec2` varchar(45) DEFAULT NULL,
  `spec3` varchar(45) DEFAULT NULL,
  `factory_id` int(10) unsigned DEFAULT NULL COMMENT '厂家，钢厂',
  `factory_name` varchar(45) DEFAULT NULL,
  `city_id` int(10) unsigned DEFAULT NULL COMMENT '城市',
  `city_name` varchar(60) DEFAULT NULL,
  `price` decimal(18,6) DEFAULT NULL,
  `weight` decimal(18,6) DEFAULT NULL,
  `weight_concept` varchar(255) DEFAULT NULL COMMENT '计重方式',
  `warehouse_id` int(10) DEFAULT NULL,
  `warehouse_name` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT='采购需求明细表，购物车使用';

-- ----------------------------
-- Records of temp_requirement_item_dto
-- ----------------------------
INSERT INTO `temp_requirement_item_dto` VALUES ('1', 'GUID_000000000H', 'PICK102640_07120301', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', null, '25.600000', '过磅', '1', '三里洋', '镀锌量60');
INSERT INTO `temp_requirement_item_dto` VALUES ('2', 'GUID_000000000I', 'PICK102640_07120301', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', null, '25.600000', '过磅', '1', '三里洋', '镀锌量60');
INSERT INTO `temp_requirement_item_dto` VALUES ('3', 'GUID_000000000J', 'PICK102640_07120301', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', null, '25.600000', '过磅', '1', '三里洋', '镀锌量60');
INSERT INTO `temp_requirement_item_dto` VALUES ('4', 'GUID_000000000K', 'SM102640_07120301', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', '85.000000', '25.600000', '过磅', '1', '三里洋', null);
INSERT INTO `temp_requirement_item_dto` VALUES ('5', 'GUID_000000000L', 'SM102640_07120301', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', '85.000000', '25.600000', '过磅', '1', '三里洋', null);
INSERT INTO `temp_requirement_item_dto` VALUES ('6', 'GUID_000000000M', 'SM102640_07120301', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', '85.000000', '25.600000', '过磅', '1', '三里洋', null);
INSERT INTO `temp_requirement_item_dto` VALUES ('7', 'GUID_000000000Z', 'SM102640_07120302', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', '80.000000', '25.600000', '过磅', '1', '三里洋', '');
INSERT INTO `temp_requirement_item_dto` VALUES ('8', 'GUID_000000000X', 'SM102640_07120302', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', '82.000000', '25.600000', '过磅', '1', '三里洋', '');
INSERT INTO `temp_requirement_item_dto` VALUES ('9', 'GUID_000000000C', 'SM102640_07120302', 'category_uuid', '镀锌卷板', 'material_uuid', 'B235', '2.5', '1250', 'C', '1', '韩国浦项/中天', '1', '杭州', '85.000000', '25.600000', '过磅', '1', '三里洋', '');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) NOT NULL,
  `name` varchar(20) DEFAULT NULL COMMENT '姓名',
  `mobile` varchar(11) NOT NULL COMMENT '手机号',
  `password` varchar(32) DEFAULT NULL COMMENT '密码',
  `source` varchar(10) DEFAULT NULL COMMENT '用户来源 CBMS，MARKET，APP',
  `status` char(1) NOT NULL DEFAULT '1' COMMENT '状态 0禁用 1启用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_deleted` char(1) DEFAULT 'N' COMMENT '删除标记N未删除Y已删除',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) NOT NULL,
  `modification_number` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `mobile_UNIQUE` (`mobile`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=1107 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES ('1105', 'GUID_000000001O', '13500000001', '13500000001', '123456', 'MARKET', '1', null, 'N', '2016-05-05 20:19:07', 'SYS_USER', '2016-05-05 20:19:07', 'SYS_USER', '0');
INSERT INTO `user` VALUES ('1106', 'GUID_000000001P', '13500000002', '13500000002', '123456', 'MARKET', '1', '', 'N', '2016-05-05 20:19:07', 'SYS_USER', '2016-05-05 20:19:07', 'SYS_USER', '0');

/* ***********************************
Version: 10
Added by: huangsenfa
Added at: 2016-05-10 10:00:29
Description: 数据库guid 字段内容区分大小写
************************************ */

ALTER TABLE base_feedback
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE base_sms_valid_code
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;


ALTER TABLE base_system_operation_log
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;


ALTER TABLE busi_requirement
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;


ALTER TABLE busi_requirement_item
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE busi_requirement_status_change_record
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE demo
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE mkt_cart
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE mkt_search_history
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE mkt_search_preference
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE temp_requirement_dto
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE temp_requirement_item_dto
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE user
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

ALTER TABLE user_subscrib
CHANGE COLUMN `guid` `guid` VARCHAR(45) BINARY NOT NULL ;

/* ***********************************
Version: 11
Added by: maoyehui
Added at: 2016-05-12 16:03:59
Description: 采购管理mock数据
************************************ */
/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : ec2.0

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2016-05-12 16:02:28
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for temp_consign_order_dto
-- ----------------------------
DROP TABLE IF EXISTS `temp_consign_order_dto`;
CREATE TABLE `temp_consign_order_dto` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code` varchar(45) DEFAULT NULL COMMENT '单号',
  `account_name` varchar(45) DEFAULT NULL COMMENT '买家企业名称',
  `contact_name` varchar(45) DEFAULT NULL COMMENT '联系人姓名',
  `contact_tel` varchar(45) DEFAULT NULL COMMENT '联系人电话',
  `total_weight` decimal(18,6) DEFAULT NULL COMMENT '总重量',
  `actual_pick_weight` decimal(18,6) DEFAULT NULL COMMENT '总实提重量',
  `total_amount` decimal(18,6) DEFAULT NULL COMMENT '总金额',
  `status` varchar(45) DEFAULT NULL COMMENT '    TO_BE_RELATED("TOBERELATED","待付款"),\r\n    TO_BE_SECONDARY("TOBESECONDARY", "待结算"),\r\n    FINISHED("FINISHED", "交易完成"),\r\n    CLOSED("CLOSED", "交易关闭");',
  `time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '时间（下单时间/关联时间/二结时间/关闭时间）',
  `pay_type` varchar(255) DEFAULT NULL COMMENT '支付方式',
  `contract_url` varchar(255) DEFAULT NULL COMMENT '查看合同url',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uix_busi_consign_order_code` (`code`),
  KEY `IDX_OPERATOR_ID_STATUS` (`status`),
  KEY `IDX_account_id_owner_id_STATUS` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8 COMMENT='寄售交易订单';

-- ----------------------------
-- Records of temp_consign_order_dto
-- ----------------------------
INSERT INTO `temp_consign_order_dto` VALUES ('127', 'DD-HD-000013-1604-000023', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', null, '33.000000', 'TOBESECONDARY', '2016-04-11 09:41:29', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('128', 'DD-HD-000013-1604-000024', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', null, '222.000000', 'TOBESECONDARY', '2016-04-11 10:16:41', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('129', 'DD-HD-000013-1604-000025', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', null, '1.000000', 'TOBERELATED', '2016-04-11 14:26:39', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('130', 'DD-HD-000013-1604-000026', '杭州钢为网络科技有限公司', '发发', '18767122589', '1.000000', null, '1.000000', 'TOBERELATED', '2016-04-11 14:27:44', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('131', 'DD-HD-000000-1604-000027', '杭州钢为网络科技有限公司', '随便', '13500000069', '1.000000', null, '1.000000', 'TOBERELATED', '2016-04-11 14:31:02', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('134', 'DD-HD-000013-1604-00002A', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', null, '222.000000', 'TOBESECONDARY', '2016-04-15 13:36:20', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('135', 'DD-HD-000013-1604-00002B', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', '1.000000', '222.000000', 'FINISHED', '2016-04-18 09:36:06', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('143', 'DD-HD-000013-1604-00002J', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', null, '111.000000', 'TOBERELATED', '2016-04-25 09:23:18', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('144', 'DD-HD-000013-1604-00002K', '杭州钢为网络科技有限公司', '阿发', '13500000001', '5.000000', null, '17500.000000', 'TOBESECONDARY', '2016-04-25 09:31:15', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('145', 'DD-HD-000013-1604-00002L', '杭州钢为网络科技有限公司', '阿发', '13500000001', '1.000000', null, '222.000000', 'TOBERELATED', '2016-04-25 09:58:13', '现金支付', null);
INSERT INTO `temp_consign_order_dto` VALUES ('146', 'DD-HD-000013-1604-00002M', '杭州钢为网络科技有限公司', '阿发', '13500000001', '5.000000', null, '11500.000000', 'CLOSED', '2016-04-25 10:09:29', '现金支付', null);

-- ----------------------------
-- Table structure for temp_consign_order_items_dto
-- ----------------------------
DROP TABLE IF EXISTS `temp_consign_order_items_dto`;
CREATE TABLE `temp_consign_order_items_dto` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) DEFAULT NULL COMMENT '订单号',
  `nsort_name` varchar(45) DEFAULT NULL COMMENT '品名',
  `material` varchar(45) DEFAULT NULL COMMENT '材质',
  `spec` varchar(45) DEFAULT NULL COMMENT '规格',
  `factory` varchar(45) DEFAULT NULL COMMENT '厂家',
  `city` varchar(45) DEFAULT NULL COMMENT '城市',
  `warehouse` varchar(45) DEFAULT NULL COMMENT '仓库',
  `weight` decimal(18,6) DEFAULT NULL COMMENT '重量',
  `weight_concept` varchar(45) DEFAULT NULL COMMENT '理计，磅计，抄码',
  `deal_price` decimal(18,6) DEFAULT NULL COMMENT '成交价',
  `actual_pick_weight` decimal(18,6) DEFAULT '0.000000' COMMENT '实际提货重量（用于二次结算）',
  PRIMARY KEY (`id`),
  KEY `IDX_ORDER_ID` (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=246 DEFAULT CHARSET=utf8 COMMENT='寄售订单商品明细';

-- ----------------------------
-- Records of temp_consign_order_items_dto
-- ----------------------------
INSERT INTO `temp_consign_order_items_dto` VALUES ('226', '127', '中厚板', 'Q235B', '1*2*3', '武钢', '乌海市', '南通', '1.000000', '理计', '33.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('227', '128', '中厚板', 'Q235B', '1*2*3', '武钢', '石家庄市', '南通', '1.000000', '理计', '222.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('228', '129', '大梁板', 'Q235B', '1*2*3', '武钢', '邯郸市', '南通', '1.000000', '理计', '1.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('229', '130', '弹簧板', 'Q235B', '1*2*3', '武钢', '石家庄市', '南通', '1.000000', '理计', '1.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('230', '131', '容器板', 'Q235B', '1*2*3', '武钢', '乌海市', '南通', '1.000000', '理计', '1.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('233', '134', '耐候板', 'Q235B', '1*2*3', '武钢', '天津市', '南通', '1.000000', '理计', '222.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('234', '135', '耐候板', 'Q235B', '1*2*3', '武钢', '石家庄市', '南通', '1.000000', '理计', '222.000000', '1.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('242', '143', '锅炉板', 'Q235B', '1*2*3', '武钢', '保定市', '南通', '1.000000', '理计', '111.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('243', '144', '容器板', 'Q235B', '1*2*3', '武钢', '石家庄市', '南通', '5.000000', '理计', '3500.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('244', '145', '热轧正平板', 'Q235B', '1*2*3', '武钢', '石家庄市', '南通', '1.000000', '理计', '222.000000', '0.000000');
INSERT INTO `temp_consign_order_items_dto` VALUES ('245', '146', '容器板', 'Q235B', '1*2*3', '武钢', '保定市', '南通', '5.000000', '理计', '2300.000000', '0.000000');


/* ***********************************
Version: 12
Added by: wangyixiao
Added at: 2016-05-16 17:10:33
Description: temp_requirement_item_dto 增加amount字段
************************************ */
ALTER TABLE `temp_requirement_item_dto`
ADD COLUMN `amount`  decimal(18,6) NULL AFTER `weight`;


/* ***********************************
Version: 13
Added by: huangsenfa
Added at: 2016-05-18 14:44:42
Description: 超市资源临时表，造数据用
************************************ */
/*
Navicat MySQL Data Transfer

Source Server         : cbms
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : ec2.0

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2016-05-18 14:40:02
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for temp_resource
-- ----------------------------
DROP TABLE IF EXISTS `temp_resource`;
CREATE TABLE `temp_resource` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(45) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `category_uuid` varchar(45) DEFAULT NULL COMMENT '品名',
  `category_name` varchar(45) DEFAULT NULL,
  `material_uuid` varchar(45) DEFAULT NULL COMMENT '材质',
  `material_name` varchar(45) DEFAULT NULL,
  `spec1` varchar(45) DEFAULT NULL COMMENT '规格1',
  `spec2` varchar(45) DEFAULT NULL,
  `spec3` varchar(45) DEFAULT NULL,
  `factory_id` int(10) unsigned DEFAULT NULL COMMENT '厂家，钢厂',
  `factory_name` varchar(45) DEFAULT NULL,
  `city_id` int(10) unsigned DEFAULT NULL COMMENT '城市',
  `city_name` varchar(60) DEFAULT NULL,
  `price` decimal(18,6) DEFAULT NULL,
  `weight_concept` varchar(255) DEFAULT NULL COMMENT '计重方式',
  `warehouse_id` int(10) DEFAULT NULL,
  `warehouse_name` varchar(255) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) DEFAULT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) DEFAULT NULL,
  `modification_number` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `guid_UNIQUE` (`guid`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COMMENT='超市资源临时表，造数据用';


/* ***********************************
Version: 14
Added by: maoyehui
Added at: 2016-05-19 18:42:30
Description: 用户登录状态删除和未登录状态删除标记分开
************************************ */
ALTER TABLE `ec2.0`.`mkt_search_history` 
CHANGE COLUMN `is_deleted` `is_user_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除' ,
ADD COLUMN `is_cookie_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除' AFTER `city_name`;


/* ***********************************
Version: 15
Added by: maoyehui
Added at: 2016-05-20 17:15:51
Description: 猜你喜欢存储过程
************************************ */
CREATE PROCEDURE `proc_do_search_preferences`()
BEGIN 
-- 需要定义接收游标数据的变量 
DECLARE _today DATETIME DEFAULT NOW();
DECLARE _user_guid, _category_uuid, _category_name VARCHAR(45);
DECLARE _material_uuid, _material_name, _spec1, _spec2, _spec3, _city_id, _city_name, _factory_id, _factory_name VARCHAR(2000);
DECLARE _count INT;
DECLARE	_created, _last_updated DATETIME;
-- 遍历数据结束标志
DECLARE done INT DEFAULT FALSE;
-- 游标
DECLARE cur CURSOR FOR
(			
		SELECT user_guid,category_uuid,category_name,SUM(count) count,
			 MIN(created) created,MAX(last_updated) last_updated
		FROM (
			SELECT user_guid,category_uuid,category_name,created,last_updated,1 count  
			FROM mkt_search_history 
			WHERE created < _today AND is_deleted_for_preference = 'N' AND user_guid IS NOT NULL
			UNION ALL
			SELECT user_guid,category_uuid,category_name,created,last_updated,count 
			FROM mkt_search_preference 
			WHERE is_deleted = 'N'
		) TT 
		GROUP BY user_guid, category_uuid
);
-- 将结束标志绑定到游标
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

-- 打开游标
OPEN cur;
-- 开始循环
read_loop: LOOP
-- 提取游标里的数据；
	FETCH cur INTO _user_guid, _category_uuid, _category_name, _count, _created, _last_updated;
-- 声明结束的时候
	IF done THEN
      LEAVE read_loop;
  END IF;
-- 这里做你想做的循环的事件
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'material_uuid') INTO _material_uuid;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'material_name') INTO _material_name;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'spec1') INTO _spec1;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'spec2') INTO _spec2;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'spec3') INTO _spec3;	
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'city_id') INTO _city_id;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'city_name') INTO _city_name;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'factory_id') INTO _factory_id;
	SELECT doArrayStr_search_preferences(_user_guid, _category_uuid, 'factory_name') INTO _factory_name;
-- DELETE RECORD
	DELETE FROM mkt_search_preference WHERE user_guid = _user_guid AND category_uuid = _category_uuid;
-- INSERT NEW RECORD
	INSERT INTO mkt_search_preference(guid, user_guid, category_uuid, category_name, material_uuid, material_name, 
		spec1, spec2, spec3, city_id, city_name, factory_id, factory_name, count, is_show, created, created_by, last_updated, last_updated_by)
		VALUES(UUID(), _user_guid, _category_uuid, _category_name, _material_uuid, _material_name, _spec1, _spec2, _spec3, 
					_city_id, _city_name, _factory_id, _factory_name, _count, 'N', _created, 'SYSTEM', _last_updated, 'SYSTEM');
END LOOP;
-- 关闭游标
CLOSE cur;

-- 设置是否显示
SET @num = 0, @_user = '';
UPDATE mkt_search_preference SET is_show = 'Y' 
WHERE id IN (
   SELECT id 
   FROM(
		  SELECT IF (@_user = user_guid, @num:=@num + 1, @num:=1) rank, @_user := user_guid, x.id
		  FROM (
			  SELECT id, user_guid
			  FROM mkt_search_preference
			  WHERE user_guid IS NOT NULL AND is_deleted = 'N' AND count >= 3
			  ORDER BY user_guid, count DESC, last_updated DESC, id DESC
		  ) x
   ) xx
   WHERE rank < 6
);

-- 清理搜索记录表中多余数据(每个客户或者cookieId最多保留5条)
SET @num = 0, @_user = '';
DELETE FROM mkt_search_history
WHERE id NOT IN (
   SELECT id 
   FROM(
		  SELECT IF (@_user = user_guid, @num:=@num + 1, @num:=1) rank, @_user := user_guid, x.*
		  FROM (
			  SELECT MAX(id) id, user_guid, MAX(created) created 
			  FROM mkt_search_history
			  WHERE user_guid IS NOT NULL
			  GROUP BY user_guid, category_uuid, material_uuid, spec1 ,spec2 ,spec3, factory_id, city_id
			  ORDER BY user_guid, MAX(created) DESC, MAX(id) DESC
		  ) x
   ) xx
   WHERE rank < 6
	 UNION
   SELECT * FROM(
		 SELECT id
		 FROM mkt_search_history
		 WHERE user_guid IS NULL
   ) yy
);
SET @num = 0, @_user = '';

-- 设置截止时间之前的所有搜索记录不再计算偏好
UPDATE mkt_search_history 
SET is_deleted_for_preference = 'Y'
WHERE created < _today and user_guid IS NOT NULL;

-- 删除过期的猜你喜欢（90天未更新的记录）
DELETE FROM mkt_search_preference
WHERE last_updated < DATE_SUB(_today,INTERVAL 90 DAY);

END

/* ***********************************
Version: 16
Added by: maoyehui
Added at: 2016-05-20 17:16:30
Description: 猜你喜欢用到的拼接字段函数
************************************ */
CREATE FUNCTION `func_split_TotalLength`(f_string varchar(1000),f_delimiter varchar(5)) RETURNS int(11)
BEGIN 
    # 计算传入字符串的总length 
    return 1+(length(f_string) - length(replace(f_string,f_delimiter,''))); 
END;


CREATE FUNCTION `func_split`(f_string varchar(1000),f_delimiter varchar(5),f_order int) RETURNS varchar(255) CHARSET utf8
BEGIN 
    # 拆分传入的字符串，返回拆分后的新字符串 
        declare result varchar(255) default ''; 
        set result = reverse(substring_index(reverse(substring_index(f_string,f_delimiter,f_order)),f_delimiter,1)); 
        return result; 
END;

CREATE FUNCTION `f_split`(_str varchar(2000), _type varchar(20)) RETURNS varchar(2000) CHARSET utf8
BEGIN
DECLARE _split varchar(2) DEFAULT ',';
DECLARE _spec_split varchar(2) DEFAULT '-';
DECLARE _return varchar(2000) DEFAULT '';
DECLARE _temp varchar(50) DEFAULT '';
DECLARE _range_cnt, cnt, i, j INT DEFAULT 0;
DECLARE t1, t2 varchar(10) DEFAULT 0; 
DECLARE max, min varchar(10) DEFAULT -1; 

IF(_str IS NULL) THEN RETURN NULL; END IF;
SET _range_cnt = func_split_TotalLength(_str, _spec_split) - 1;
SET cnt = func_split_TotalLength(_str, _split); 

IF(_type in ('material_uuid', 'material_name', 'spec1', 'city_id', 'city_name', 'factory_id', 'factory_name')) THEN

	WHILE i < cnt 
	DO 
		SET i = i + 1; 
		SET _temp = func_split(_str, _split, i);
		IF NOT FIND_IN_SET(_temp, _return) THEN
			SET _return = CONCAT(_return, _split, _temp);
		END IF;
	END WHILE;

	IF LENGTH(_return) > 0 THEN 
		SET _return = SUBSTRING(_return , 2); 
	END IF; 

ELSEIF(_type in ('spec2', 'spec3')) THEN

	IF _range_cnt = 0 OR Length(func_split(_str, _split, 1)) = 36 THEN	
		WHILE i < cnt 
		DO 
			SET i = i + 1; 
			SET _temp = func_split(_str, _split, i);
			IF _temp = 'C' THEN RETURN 'C'; 
			ELSEIF NOT FIND_IN_SET(_temp, _return) THEN
				SET _return = CONCAT(_return, _split, _temp);
			END IF;
		END WHILE;
		IF LENGTH(_return) > 0 THEN 
			SET _return = SUBSTRING(_return , 2); 
		END IF;
	ELSE
		WHILE i < cnt 
		DO
			 SET i = i + 1;
			 SET _temp = func_split(_str, _split, i);
			 IF(func_split_TotalLength(_temp, _spec_split) > 1) THEN
				 SET t1 = func_split(_temp, _spec_split, 1);
				 SET t2 = func_split(_temp, _spec_split, 2);
				 IF(t1 = 'C' OR t2 = 'C') THEN RETURN 'C'; END IF;
				 IF min = -1 THEN SET min = t1; ELSEIF t1 * 1 < min * 1 THEN SET min = t1; END IF;
				 IF max = -1 THEN SET max = t2; ELSEIF t2 * 1 > max * 1 THEN SET max = t2; END IF;
			 ELSE 
				 IF(_temp = 'C') THEN RETURN 'C'; END IF;
				 IF min = -1 THEN SET min = _temp; ELSEIF _temp * 1 < min * 1 THEN SET min = _temp; END IF;
				 IF max = -1 THEN SET max = _temp; ELSEIF _temp * 1 > max * 1 THEN SET max = _temp; END IF;
			 END IF;
		END WHILE;
		SET _return = CONCAT(min, '-', max); 
	END IF;

END IF;

SET i = 0, j = 0, t1 = 0, t2 = 0, max = -1, min = -1;
RETURN _return;
END;

CREATE FUNCTION `doArrayStr_search_preferences`(_user_guid VARCHAR(45),
  _category_uuid VARCHAR(45),
	_fieldstr VARCHAR(100)) RETURNS varchar(2000) CHARSET utf8
BEGIN

DECLARE STR VARCHAR(2000);
	
SELECT GROUP_CONCAT(CCF) INTO STR 
FROM (
	SELECT DISTINCT(
		CASE 
		WHEN _fieldstr ='material_uuid' THEN material_uuid 
		WHEN _fieldstr ='material_name' THEN material_name  
		WHEN _fieldstr ='spec1' THEN spec1 
		WHEN _fieldstr ='spec2' THEN spec2  
		WHEN _fieldstr ='spec3' THEN spec3  
		WHEN _fieldstr ='city_id' THEN city_id  
		WHEN _fieldstr ='city_name' THEN city_name  
		WHEN _fieldstr ='factory_id' THEN factory_id
		WHEN _fieldstr ='factory_name' THEN factory_name END 
	) AS CCF  FROM 
	(
			SELECT material_uuid, material_name, spec1, spec2, spec3, city_id, city_name, factory_id, factory_name
			FROM mkt_search_history 
			WHERE created < NOW() AND is_deleted_for_preference = 'N' 
			AND user_guid = _user_guid AND category_uuid = _category_uuid
			UNION ALL
			SELECT material_uuid, material_name, spec1, spec2, spec3, city_id, city_name, factory_id, factory_name 
			FROM mkt_search_preference 
			WHERE is_deleted = 'N' AND user_guid = _user_guid AND category_uuid = _category_uuid
	) TT
)AS T
WHERE CCF IS NOT NULL;

RETURN f_split(STR, _fieldstr);

END;

/* ***********************************
Version: 18
Added by: maoyehui
Added at: 2016-05-23 15:13:29
Description: 猜你喜欢表添加是否显示字段
************************************ */
ALTER TABLE `mkt_search_preference` 
ADD COLUMN `is_show` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '显示标记 N不显示 Y显示' AFTER `count`;


/* ***********************************
Version: 19
Added by: maoyehui
Added at: 2016-05-25 15:50:54
Description: 错误 #9446 采购管理—订单“已关闭”状态的，鼠标移至状态上时要显示关闭理由后端
************************************ */
ALTER TABLE `temp_consign_order_dto` 
ADD COLUMN `close_reason` VARCHAR(45) NULL DEFAULT NULL COMMENT '关闭理由' AFTER `status`;

UPDATE `temp_consign_order_dto` 
SET `actual_pick_weight`='4', `close_reason`='不想要了,退货' WHERE `id`='146';


/* ***********************************
Version: 20
Added by: liweitao
Added at: 2016-05-30 10:58:15
Description: 
************************************ */


/* ***********************************
Version: 21
Added by: huangsenfa
Added at: 2016-05-30 17:32:54
Description: 超市全国中心城市临时数据
************************************ */
/*
Navicat MySQL Data Transfer

Source Server         : cbms
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : ec2.0

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2016-05-30 17:32:49
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for base_area
-- ----------------------------
DROP TABLE IF EXISTS `base_area`;
CREATE TABLE `base_area` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL COMMENT '区域名称',
  `center_city_id` bigint(20) DEFAULT NULL COMMENT '中心城市',
  `ref_city_ids` varchar(255) DEFAULT NULL COMMENT '相关城市id，逗号分开',
  `district` varchar(45) DEFAULT NULL COMMENT '地区，如：华中，华南等',
  `is_deleted` bit(1) DEFAULT b'0' COMMENT '是否删除：0 否；1 是。',
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(45) NOT NULL,
  `last_updated` datetime DEFAULT CURRENT_TIMESTAMP,
  `last_updated_by` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 COMMENT='区域表';

-- ----------------------------
-- Records of base_area
-- ----------------------------
INSERT INTO `base_area` VALUES ('1', '长沙地区', '177', '177', '华中', '\0', '2016-05-30 09:27:17', 'admin', '2016-05-30 09:27:17', 'admin');
INSERT INTO `base_area` VALUES ('2', '武汉地区', '159', '159', '华中', '\0', '2016-05-30 09:28:09', ' admin', '2016-05-30 09:28:09', 'admin');
INSERT INTO `base_area` VALUES ('3', '郑州地区', '142', '142', '华中', '\0', '2016-05-30 09:28:51', 'admin', '2016-05-30 09:28:42', 'admin');
INSERT INTO `base_area` VALUES ('4', '成都地区', '225', '225', '西南', '\0', '2016-05-30 09:29:41', 'admin', '2016-05-30 09:29:41', 'admin');
INSERT INTO `base_area` VALUES ('5', '重庆地区', '4', '4', '西南', '\0', '2016-05-30 09:32:32', 'admin', '2016-05-30 09:32:32', 'admin');
INSERT INTO `base_area` VALUES ('6', '佛山地区', '202', '202', '华南', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('7', '邯郸地区', '5', '5', '华北', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('8', '廊坊地区', '11', '11', '华北', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('9', '天津地区', '2', '2', '华北', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('10', '石家庄地区', '6', '6', '华北', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('11', '唐山地区', '10', '10', '华北', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('12', '杭州地区', '78', '78', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('13', '济南地区', '125', '125', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('14', '莱芜地区', '139', '139', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('15', '潍坊地区', '130', '130', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('16', '无锡地区', '64', '64', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('17', '苏州地区', '66', '66', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');
INSERT INTO `base_area` VALUES ('18', '上海地区', '3', '3', '华东', '\0', '2016-05-30 09:38:25', 'admin', '2016-05-30 09:38:25', 'admin');


/* ***********************************
Version: 22
Added by: maoyehui
Added at: 2016-05-30 20:56:02
Description: 删除标记
************************************ */
ALTER TABLE `ec2.0`.`mkt_search_history` 
ADD COLUMN `is_deleted` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '删除标记N未删除Y已删除' AFTER `is_user_deleted`;


/* ***********************************
Version: 23
Added by: gelinzhong
Added at: 2016-06-01 16:19:49
Description: 
************************************ */
ALTER TABLE `mkt_search_history`
MODIFY COLUMN `material_uuid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '材质，可多选，逗号隔开' AFTER `category_name`;


/* ***********************************
Version: 24
Added by: maoyehui
Added at: 2016-06-02 15:28:54
Description: 去掉需求单城市必选
************************************ */
ALTER TABLE `busi_requirement_item`
MODIFY COLUMN `city_id`  int(10) UNSIGNED NULL COMMENT '城市' AFTER `factory_name`,
MODIFY COLUMN `city_name`  varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `city_id`;


/* ***********************************
Version: 25
Added by: gelinzhong
Added at: 2016-06-06 10:02:33
Description: 删除用户表中的密码字段，不在本系统做认证
************************************ */
ALTER TABLE `user`
DROP COLUMN `password`;


/* ***********************************
Version: 26
Added by: maoyehui
Added at: 2016-06-07 11:31:43
Description: 猜你喜欢字段长度修改
************************************ */
ALTER TABLE `mkt_search_preference`
MODIFY COLUMN `material_uuid`  varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '材质，可多选，逗号隔开' AFTER `category_name`,
MODIFY COLUMN `material_name`  varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `material_uuid`,
MODIFY COLUMN `spec1`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '规格可多选' AFTER `material_name`,
MODIFY COLUMN `spec2`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '单选或区间' AFTER `spec1`,
MODIFY COLUMN `spec3`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '单选或区间' AFTER `spec2`,
MODIFY COLUMN `factory_name`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `factory_id`,
MODIFY COLUMN `city_id`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '城市id，多选，逗号隔开' AFTER `factory_name`,
MODIFY COLUMN `city_name`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `city_id`;

/* ***********************************
Version: 27
Added by: maoyehui
Added at: 2016-06-07 14:43:35
Description: 修复history表字段长度太短的问题
************************************ */
ALTER TABLE `mkt_search_history`
MODIFY COLUMN `material_uuid`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '材质，可多选，逗号隔开' AFTER `category_name`,
MODIFY COLUMN `material_name`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `material_uuid`,
MODIFY COLUMN `spec1`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '规格可多选' AFTER `material_name`,
MODIFY COLUMN `spec2`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '单选或区间' AFTER `spec1`,
MODIFY COLUMN `spec3`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '单选或区间' AFTER `spec2`,
MODIFY COLUMN `factory_id`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '钢厂，多选，逗号隔开' AFTER `spec3`,
MODIFY COLUMN `factory_name`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `factory_id`,
MODIFY COLUMN `city_id`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '城市id，多选，逗号隔开' AFTER `factory_name`,
MODIFY COLUMN `city_name`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `city_id`;


/* ***********************************
Version: 28
Added by: gelinzhong
Added at: 2016-06-13 14:58:08
Description: 需主表增加单号唯一索引
************************************ */
ALTER TABLE `busi_requirement`
MODIFY COLUMN `code`  varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '需求单号' AFTER `guid`,
ADD UNIQUE INDEX `code_UNIQUE` (`code`) USING BTREE ;


/* ***********************************
Version: 29
Added by: gelinzhong
Added at: 2016-06-17 09:14:36
Description: 增加文件url长度，因为文件路径变成全路径了
************************************ */
ALTER TABLE `busi_requirement`
MODIFY COLUMN `file_url`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '采购清单文件地址,多文件时逗号隔开' AFTER `request`;


/* ***********************************
Version: 30
Added by: gelinzhong
Added at: 2016-06-17 11:38:19
Description: 购物车和需求单增加仓库字段
************************************ */
ALTER TABLE `mkt_cart`
ADD COLUMN `warehouse_id`  int NOT NULL AFTER `city_name`,
ADD COLUMN `warehouse_name`  varchar(60) NOT NULL AFTER `warehouse_id`;

ALTER TABLE `busi_requirement_item`
ADD COLUMN `warehouse_id`  int NULL AFTER `city_name`,
ADD COLUMN `warehouse_name`  varchar(60) NULL AFTER `warehouse_id`;

/* ***********************************
Version: 31
Added by: gelinzhong
Added at: 2016-07-07 08:54:26
Description: 去掉需求单明细中的城市非空要求，因为来自APP的再来一单请求无法给出城市属性
************************************ */
ALTER TABLE `busi_requirement_item`
MODIFY COLUMN `city_id`  int(10) UNSIGNED NULL COMMENT '城市' AFTER `factory_name`,
MODIFY COLUMN `city_name`  varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `city_id`;



/* ***********************************
Version: 32
Added by: maoyehui
Added at: 2016-07-12 09:32:33
Description: 删掉多余的表
************************************ */
DROP TABLE base_area,
 base_city,
 base_factory,
 base_feedback,
 base_warehouse,
 common_category,
 common_category_group,
 common_category_materials,
 common_category_norms,
 common_group_for_category,
 common_materials,
 common_site,
 common_norms,
 cust_resource,
 cust_resource_norms,
 temp_consign_order_dto,
 temp_consign_order_items_dto,
 temp_requirement_dto,
 temp_requirement_item_dto,
 temp_resource,
 user_subscrib;

/* ***********************************
Version: 33
Added by: gelinzhong
Added at: 2016-07-15 13:53:14
Description: mq日志表
************************************ */
CREATE TABLE `busi_mq_log` (
`id`  int NOT NULL AUTO_INCREMENT ,
`modual`  varchar(30) NOT NULL COMMENT '操作模块。\r\n1.ADD_CBMS_CONTACT(超市新增用户推送到cbms);\r\n2.UPDATE_CBMS_CONTACT(超市更新用户推送到cbms);\r\n3.ADD_MARKET_USER_ID(超市推送新增联系人的超市userId给CBMS);\r\n4.ADD_MARKET_USER(cbms新增用户推送到超市);\r\n5.UPDATE_MARKET_USER(cbms更新用户推送到超市);\r\n6.CHANGE_CONTACT_STATUS(CBMS禁用/启用联系人);\r\n7.MARKET_REQUIREMENT(超市推送需求单到分检);\r\n8.ASS_REQUIREMENT(分检推送需求单到超市);\r\n9.ASS_REQUIREMENT_STATUS(分拣更新超市需求单状态);\r\n10.SM_REQUIREMENT_STATUS(找货更新超市需求单状态);\r\n11.CBMS_REQUIREMENT_STATUS(CBMS更新超市需求单状态);' ,
`remote_sys`  varchar(10) NOT NULL COMMENT '对方系统，PICK,CBMS,SMART' ,
`content`  varchar(1000) NOT NULL ,
`is_success`  char(1) NOT NULL COMMENT '操作是否成功Y是N否' ,
`error_msg`  varchar(1000) NULL ,
`created`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间点' ,
PRIMARY KEY (`id`)
)
;


/* ***********************************
Version: 34
Added by: gelinzhong
Added at: 2016-07-19 17:07:55
Description: 注意：是cas_db！
************************************ */
超市的CAS数据需要增加一个字段，脚本如下：
-- ----------------------------
-- Upgrade
-- ----------------------------
ALTER TABLE `user`
ADD COLUMN `dynamic_password_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '密码创建时间' AFTER `dynamic_password_expired`;

ALTER TABLE `user`
CHANGE COLUMN `dynamic_password_created` `dynamic_password_created` DATETIME NULL DEFAULT NULL COMMENT '密码创建时间' ;

/* ***********************************
Version: 35
Added by: huangsenfa
Added at: 2016-07-22 14:50:36
Description: 需求单号生成器表
************************************ */
CREATE TABLE `global_requirement_code` (
`id`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
`created`  datetime  NULL ,
PRIMARY KEY (`id`)
)
ENGINE=InnoDB
;

/* ***********************************
Version: 37
Added by: wangyixiao
Added at: 2016-08-24 14:36:28
Description: app登录日志表
************************************ */
CREATE TABLE `busi_app_login_log` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `user_id` int(10) NOT NULL COMMENT '用户id',
  `token` varchar(40) NOT NULL COMMENT '用户token',
  `created` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间点',
  `last_updated` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间点',
  `modification_number` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) 
;

DELETE FROM pyramid_db_version;
INSERT INTO pyramid_db_version(version) VALUES('37');