 
-- ----------------------------
-- Describe: 新增权限（喜艳）
-- Author: Rolyer Luo
-- Date: 2015-11-19 11:57
-- ----------------------------
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('提交', 'invoice:in:inputinvoice:send:submitInvoice', '/invoice/in/send.html#submitInvoice', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('修改', 'invoice:in:inputinvoice:send:edit', '/invoice/in/send.html#edit', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('复制', 'invoice:in:inputinvoice:send:copy', '/invoice/in/send.html#copy', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('关联', 'invoice:in:inputinvoice:send:relate', '/invoice/in/send.html#relate', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('删除', 'invoice:in:inputinvoice:send:delete', '/invoice/in/send.html#delete', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('查看关联', 'invoice:in:inputinvoice:send:viewRelate', '/invoice/in/send.html#viewRelate', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('取消关联', 'invoice:in:inputinvoice:send:cancelelation', '/invoice/in/send.html#cancelelation', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('添加', 'invoice:in:inputinvoice:send:add', '/invoice/in/send.html#add', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('取消选择', 'invoice:in:inputinvoice:send:assign:cancelSelect', '/invoice/in/send.html#cancelSelect', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('系统推荐', 'invoice:in:inputinvoice:send:assign:sysSuggestion', '/invoice/in/send.html#sysSuggestion', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);
INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('确定', 'invoice:in:inputinvoice:send:assign:enter', '/invoice/in/send.html#enter', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);

INSERT INTO acl_permission (name, code, url, parent_id, created, created_by, last_updated, last_updated_by, modification_number, row_id, parent_row_id) VALUES ('编辑', 'invoice:in:inputinvoice:send:modify', '/invoice/in/send.html#modify', 125, current_timestamp, 'admin', current_timestamp, 'admin', 0, null, null);